### ISSUE TITLE
Is there a problem between this mod and Food Funk?

### ISSUE THREAD

**Issue by Wynn33** [alcatrazEscapee/no-tree-punching#101]
Well, i have a modpack with 126 mods (No tree Punching included), yesterday i added two mods: Weather, Storms and tornadoes and Food Funk. I started went to the launcher and started minecraft and it says that No tree punching is no opening in the second phase of initialization of mods, then i tried to unable weather storms and tornadoes to see if that was the problem and nope, it was the same result so i tried this time to unable Food Funk and active the other one and it worked, so the conclusion i can get is that they are incompatible but it doesn't say it in any part

What does this means?

I will leave the last crash report and the version of this mod is 2.0.20.
[crash-2019-11-09_16.18.14-client.txt](https://github.com/alcatrazEscapee/no-tree-punching/files/3827636/crash-2019-11-09_16.18.14-client.txt)

My modpack: https://www.curseforge.com/minecraft/modpacks/primus-modpack

**Comment by alcatrazEscapee** [comment]
By the looks of this, this is a problem on Food Funks side.

**Comment by alcatrazEscapee** [comment]
If there's no more updates...
