### ISSUE TITLE
Config option for vessels in vessels

### ISSUE THREAD

**Issue by Exsolutus** [alcatrazEscapee/no-tree-punching#102]
It would be great to have a config option to disable the placement of clay vessels inside other clay vessels.

**Comment by Gliese-832-c** [comment]
I was about to report this. It breaks the game by allowing infinite inventory space in the first 30 minutes of gameplay, maybe an hour if there's no clay nearby. I even thought about disabling the small clay vessel in my modpack. This really needs to be a feature.

**Comment by alcatrazEscapee** [comment]
Not going to be doing any more development on 1.12, sorry.
