### ISSUE TITLE
Lycanites paxel not recognised as valid tool

### ISSUE THREAD

**Issue by Chalmes** [alcatrazEscapee/no-tree-punching#104]
Testing with lycanitesmobs-1.12.2-2.0.1.6 (RLCraft 2.8 test build 5+) and notreepunching-2.0.20 though i suspect the issue is the same with any released version of Lycanites.  Have tested in a 
standalone instance with just Forge, Lycanites and NTP.

Paxel created using an equipment forge is not recognised as a valid tool for breaking wood and stone, the blocks break, but no drops when NTP is installed.

![image](https://user-images.githubusercontent.com/2739794/69109894-ed175180-0add-11ea-8e9a-2de17e72986d.png)

![image](https://user-images.githubusercontent.com/2739794/69109902-f30d3280-0add-11ea-9041-d9d7360e7cb1.png)

**Comment by Shivaxi** [comment]
Lycanite fixed this on his end already

**Comment by alcatrazEscapee** [comment]
Good to know

**Comment by Plasman888** [comment]
The projectE morning star also isn't recognised as a valid tool
