### ISSUE TITLE
can't cut leather armor if it's not full durability

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#105]
as the title says you cannot cut leather armor with a knife unless it has full durability.  if it has any damage, it won't get cut by the knife.  not sure if this is intended or not so thought i'd post

**Comment by alcatrazEscapee** [comment]
Yes this is intentional, as otherwise you'd be able to recycle damaged leather armor into it's components and re-make the armor, gaining extra durability. If it's an issue it should be craft-tweakerable to change that
