### ISSUE TITLE
Issue with this mod and modded crops

### ISSUE THREAD

**Issue by Sethery88** [alcatrazEscapee/no-tree-punching#106]
so i made a modpack, including this mod and a mod called bewitchment (this is in 1.12.2), and i noticed that when i broke my crops in bewitchment (i tried using bare hand and flint hoe, normally in bewitchment you can use anything, including bare hand) nothing would drop. no crops. no seeds. nothing. i tried added and subtracting mods until i found out this mod was causing it. now with only the 3 mods (alcatrazcore, bewitchment, and this) it wont work. i also tried it without this mod, wherein it worked. this may also involve other modded crops, although i havent tried. do you know what is causing this? (sorry for the long paragraph)

**Comment by alcatrazEscapee** [comment]
The titular feature of this mod prevents block drops from any blocks which aren't broken with the correct tool (and somehow these crops seem to be caught up in that). The solution is to whitelist those blocks in the NTP config.
