### ISSUE TITLE
[CraftTweaker] Firepit in-world recipes?

### ISSUE THREAD

**Issue by Izbrannik** [alcatrazEscapee/no-tree-punching#107]
Im making my own modpack with Realistic Torches installed. The "firepit-way" of obtaining torches breaks the entire meaning of the aforementioned mod, as you can get vanilla, permanent torches in an early-game stage. Please, can you make it possible to add/remove in-world firepit recipes? This would be helpful for me and other modpack-creators.

Also, can i use your mod?

**Comment by aezephyr** [comment]
May I second this request?  I'm here also looking for answers to how I can integrate no tree punching with Realistic Torches.  Craft tweaker changes to in-world recipes would be perfect!

Thanks, and thanks for such a great mod; nostalgia for TFC.

**Comment by Izbrannik** [comment]
1) i'm not author of the mod
2) you can "second" my suggestion


чт, 6 февр. 2020 г. в 06:03, aezephyr <notifications@github.com>:

**Comment by alcatrazEscapee** [comment]
See #98
