### ISSUE TITLE
[Thermal Dynamics] Game crashes when i click RMB on a pipes with the axe

### ISSUE THREAD

**Issue by Izbrannik** [alcatrazEscapee/no-tree-punching#108]
![2020-01-02_15 24 44](https://user-images.githubusercontent.com/39626601/71657825-129da900-2d74-11ea-9313-ee8685d3c804.png)

Everytime i click right mouse button on a pipes (from Thermal Dynamics) while holding axe or any item that have the same behaviour game crashes. I don't know why this happens but it is.
I think what is happening is that game tries to "chop" the pipe but can't as there is no result from such action and it crashes.
Anyway, log is here:

[crash-2020-01-02_15.15.07-client.txt](https://github.com/alcatrazEscapee/no-tree-punching/files/4015241/crash-2020-01-02_15.15.07-client.txt)

**Comment by MagmaSlime123** [comment]
This ain't gonna be fixed. No updates for almost a year.

**Comment by alcatrazEscapee** [comment]
Not going to be doing any more development on 1.12, sorry.
