### ISSUE TITLE
Fire starter deletes blocks above its target.

### ISSUE THREAD

**Issue by 123mind123** [alcatrazEscapee/no-tree-punching#113]
If you target the bottom block of a 2 block high wall of stone then the top block will be deleted and replaced with fire.

**Comment by MagmaSlime123** [comment]
This ain't gonna be fixed. No updates for almost a year.

**Comment by alcatrazEscapee** [comment]
Not going to be doing any more development on 1.12, sorry.

**Comment by egdg5000** [comment]
This is not only a bug in version 1.12, but also in version 1.16.4. With the fire starter you could break the bedrock roof because it just replaces the block above with fire.
