### ISSUE TITLE
Getting planks with an axe wont work.

### ISSUE THREAD

**Issue by MagmaSlime123** [alcatrazEscapee/no-tree-punching#114]
As the RLCraft Wiki says, you can rightclick logs with an axe for wood.

However, in a pack I'm developing, nothing happens when rightclicking logs of any kind with any axe type.

https://rlcraft.fandom.com/wiki/No_Tree_Punching

*Bet this'll never be answered since this mod's been inactive for almost a year.*

**Comment by alcatrazEscapee** [comment]
> Bet this'll never be answered since this mod's been inactive for almost a year.

How much are you willing to bet ;)
