### ISSUE TITLE
Fix the Basalt rock and Cobblestone names.

### ISSUE THREAD

**Issue by MagmaSlime123** [alcatrazEscapee/no-tree-punching#115]
*Bet this'll never be fixed since this hasn't been updated for almost a year now.*

![2020-05-18_09 28 24](https://user-images.githubusercontent.com/51277766/82237174-1c224a80-98ea-11ea-88c9-b7c92fc38f43.png)
![2020-05-18_09 28 27](https://user-images.githubusercontent.com/51277766/82237177-1d537780-98ea-11ea-98e3-2f402cc198b3.png)

**Comment by alcatrazEscapee** [comment]
Not going to be doing any more development on 1.12 - I appreciate your passive aggressive comments on every one of my issues but have no idea what you were trying to achieve?

**Comment by MagmaSlime123** [comment]
The names are bugged. This is the issue.
