### ISSUE TITLE
Right-clicking with an axe on Applied Energistics 2 glass cable blocks causes crash

### ISSUE THREAD

**Issue by KirikaAetheria** [alcatrazEscapee/no-tree-punching#116]
While having an axe in hand, right-clicking on an AE2 glass cable will cause a null pointer exception crash very often. I have also tried removing the shield, the same thing still happens. 

![1](https://user-images.githubusercontent.com/61053558/85228494-92c7d180-b3db-11ea-9126-2bcb04b60c81.png)
![2](https://user-images.githubusercontent.com/61053558/85228526-bd198f00-b3db-11ea-9e6d-8376707142d3.png)

Steps to reproduce:
1- place down a glass cable, whether or not it's connected to any network
2- right click on it a once/a couple of times with any axe, or any item which can perform axe functions (like draconic evolution's staff of power)
3- game will crash

**Comment by alcatrazEscapee** [comment]
Sounds like #108, either way I'm not doing any updates to 1.12 as I've just switched to (and released) a 1.15 version, sorry.

**Comment by KirikaAetheria** [comment]
ah I see. sorry to bother then
