### ISSUE TITLE
1.15.2-3.0.4 Recipe for Macuahuitl has typo. uncraftable.

### ISSUE THREAD

**Issue by ArMoReDfUrY** [alcatrazEscapee/no-tree-punching#118]
the pattern has a space missing in the bottom row.

  "pattern": [
    " IS",
    "ISI",
    "SI"

Should be:
  "pattern": [
    " IS",
    "ISI",
    "SI "

shouldn't it have a bit of string in it?
like:   P= string
  "pattern": [
    " IP",
    "ISI",
    "SI "

thanks in advance and for the great mod.

**Comment by alcatrazEscapee** [comment]
*whoops*
