### ISSUE TITLE
No initial support for underground biomes constructs

### ISSUE THREAD

**Issue by CaptainRick218** [alcatrazEscapee/no-tree-punching#119]
It's a small issue, but when you have Underground Biomes installed, (https://www.curseforge.com/minecraft/mc-mods/underground-biomes) which adds 24 types of sand and gravel, none of them are gatherable to get flint. Only vanilla sand and gravel breaks correctly. 
I know you can add items to the always breakable list, but I'd rather it be within the base mod config itself and I'd rather not have to manually type 44 items into it.
And even when I try to add it to the list, it won't work. It's just slightly annoying.
Let me know if this issue was already addressed. And I am using the latest version for 1.12.2

**Comment by alcatrazEscapee** [comment]
Sorry, not supporting 1.12 anymore.

**Comment by CaptainRick218** [comment]
oof, oh well.
