### ISSUE TITLE
Flint pickax issue 

### ISSUE THREAD

**Issue by guavagutz** [alcatrazEscapee/no-tree-punching#122]
this mod is wonderful! However, the flint pickaxes won't mine iron and since this mod completely removes stone tools, it halts progression pretty quickly! please help me out lol

**Comment by alcatrazEscapee** [comment]
What version are you using, I believe I fixed this in 1.15.2-3.0.4

**Comment by guavagutz** [comment]
I downloaded the latest release a few days ago but I’ll re-download your new 1.15 version and try it out! Thank you :)

**Comment by alcatrazEscapee** [comment]
I've tested with 3.0.4+ and it seems to be working fine. If it's still the case let me know and I'll investigate further, otherwise I'm considering this fixed.
