### ISSUE TITLE
Block Breaking Overlay

### ISSUE THREAD

**Issue by Arcan3Gaurd1an** [alcatrazEscapee/no-tree-punching#124]
Whenever breaking blocks with tools the bright white breaking overlay appears over entire screen

**Comment by alcatrazEscapee** [comment]
Excuse me? I (quite obviously) do not see this.
 - Screenshot?
 - What mods and versions are you using?
 - Are you using optifine?

I highly doubt this is anything to do with No Tree Punching because I don't touch anything to do with rendering.

**Comment by Arcan3Gaurd1an** [comment]
You're right, upon testing with other mods I to have the same issue so i'm guessing that optifine is most likely my problem. Sorry to bring up an issue that didnt have to do with the mod, i will have to figure out if i can turn off some setting or something to fix it

**Comment by alcatrazEscapee** [comment]
No worries. It sounds like it's probably optifine doing a thing. It does that sometimes...
