### ISSUE TITLE
Modded wood plank recipes not generating  

### ISSUE THREAD

**Issue by silverotter14** [alcatrazEscapee/no-tree-punching#127]
I'm using the latest version of your mod (1.15.2-3.1.1) and wood plank recipies for modded wood won't generate. The vanilla minecraft recipe (1 log  -> 4 planks) works but when I try to use the flint axe or saw recipe there's no output. I have JEI and the modded recipes don't show up there either. The logs have all the minecraft:logs tag. Is there something I need to do on my side to make it work?

Mods I use that add new trees/logs:
Atmospheric
Swamp Expansion
Upgrade Aquatic
Endergetic Expanion
Autoimmunity
Sakura Rosea
Bloomful
World of Wonder
Dynamic World
Misc Additions

None of the flint axe/saw recipes work with the wood added by these mods.

**Comment by alcatrazEscapee** [comment]
Short answer, yes, this is intentional. Recipes are data packs now, and short of explicitly adding recipes for these specific mods, they will not be automatic. Recipes for logs -> planks can't just use tags as otherwise you'll be making any birch planks from spruce logs and other nonsense.

Recipes for sticks from logs or sticks from planks *are* automatic and simply use the `minecraft:logs` tag.

**Comment by silverotter14** [comment]
What do I have to do to add the recipes?

**Comment by alcatrazEscapee** [comment]
Make a [Data Pack](https://minecraft.gamepedia.com/Data_Pack) which adds the required recipes, and removes / replaces the existing recipes from other mods.

For example, with acacia planks:
[Removing the vanilla recipe](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.15.x/src/main/resources/data/minecraft/recipes/acacia_planks.json)
[Log -> Planks with flint axe](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.15.x/src/main/resources/data/notreepunching/recipes/acacia_planks_with_flint_axe.json)
[Log -> Planks with saw](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.15.x/src/main/resources/data/notreepunching/recipes/acacia_planks_with_saw.json)

**Comment by silverotter14** [comment]
Do I place the data pack in my mods folder when I am done making it?

**Comment by alcatrazEscapee** [comment]
No. To quote the [documentation article](https://minecraft.gamepedia.com/Data_Pack) I linked, (*please do read that it will answer all your questions*).

> Data packs can be placed in the `.minecraft/saves/(world)/datapacks` folder of a world. Each data pack is either a sub-folder or a `.zip` file within the `datapacks` folder. After it is in the folder, a data pack is enabled for that world when the world is reloaded or loaded.

**Comment by silverotter14** [comment]
Thanks 😊
