### ISSUE TITLE
Compatibility with wood types from other mods (1.15.2)

### ISSUE THREAD

**Issue by ThatOmicron** [alcatrazEscapee/no-tree-punching#128]
All recipes related to the vanilla Minecraft wood types function as intended, but for modded wood types, (say, from Biomes O' Plenty) only the logs-to-sticks recipes are overwritten correctly by No Tree Punching. **Logs-to-planks recipes for modded wood types function as if the mod wasn't even installed.**

**Comment by alcatrazEscapee** [comment]
Duplicate of #127
