### ISSUE TITLE
Fire Starter Recipe is Missing 1.12

### ISSUE THREAD

**Issue by MrNoms** [alcatrazEscapee/no-tree-punching#129]
I'll preface this with the fact that I am playing this mod within RLCraft.

I decompressed the NPT jar file to find the recipe, and even took the fire starter off of the JEI black list (as well as the Aztec tool, which wan't part of this mod, but Varied Commodites?). For some reason, neither recipe is in-game and neither can be crafted; even with the Guide-API, there's an empty page after the fire starter. I assume the recipe would have gone there.

After taking the fire starter from the black list, I saw that creating the fire pit does function properly.

Is there something I could do to bring those recipes back into the game? I installed the most up-to-date version for 1.12 and that hasn't solved the problem.

**Comment by alcatrazEscapee** [comment]
1. Not supporting 1.12 anymore, sorry.
2. I'm going to take a wild guess and say RL Craft removes the recipe, probably why it was on a JEI black list in the first place. In which case it would be script editing.

**Comment by MrNoms** [comment]
Thanks for suggestion. I found the script and made the needed deletions.
