### ISSUE TITLE
Config which tools will drop Plant Fiber

### ISSUE THREAD

**Issue by ghost** [alcatrazEscapee/no-tree-punching#130]
Title says it. Plant fiber has become a great way to get string in-game without hunting spiders, but it's a real pain to be limited only to the flint knife.

Any chance we could make it so Spartan Weapons' knives will also make grass drop plant fiber?

Love the mod, thanks!

**Comment by alcatrazEscapee** [comment]
In >=1.15 this is entirely already possible. Anything earlier than that is unsupported.

- To add plant fiber conditional drops to any block, override the loot table and add an entry. [Grass Example](https://github.com/alcatrazEscapee/no-tree-punching/blob/b3bbb97a8e9cb6e504c60482a9dd035e3a0e0a5e/src/main/resources/data/minecraft/loot_tables/blocks/grass.json#L24)
- To add other mod weapons to be recognized as knives, add them to the `notreepunching:knives` tag. [Reference](https://github.com/alcatrazEscapee/no-tree-punching/wiki/Knives#configuration).
