### ISSUE TITLE
ProjectE Morning Star not recognised as a tool

### ISSUE THREAD

**Issue by Plasman888** [alcatrazEscapee/no-tree-punching#132]
![Minecraft-1122-2020-10-14-13-31](https://user-images.githubusercontent.com/71266194/95948218-bb5c5700-0e22-11eb-8fce-0c4b3d748259.gif)

**Comment by alcatrazEscapee** [comment]
Minecraft Version, No Tree Punching Version, and ProjectE Version please.

On another note, I have no idea what this morning star is meant to do, what tool are you expecting it to be recognized as?

**Comment by Plasman888** [comment]
it's basically a paxel

**Comment by Plasman888** [comment]
notreepunching-2.0.21 and ProjectE-1.12.2-PE1.4.1

**Comment by alcatrazEscapee** [comment]
Sorry, as per the project page description

> This mod is available and being maintained for Minecraft 1.15.2 and 1.16.3. It is available for 1.12 as well but discontinued and not receiving any support.
