### ISSUE TITLE
Rocks don't spawn and stone doesn't give you pebbles

### ISSUE THREAD

**Issue by YeetusShlumpedYT** [alcatrazEscapee/no-tree-punching#134]
I made a personal modpack which included this mod however in 1.16.3 there are no rock on the ground. I'm not sure if this was a problem only I had but i've tried deleting the file and reinstalling it. I've tried going into the config and boosting up the spawn. But it still hasn't spawned any stones. As well as I can't break grass, sand, or dirt. If you could tell me whats wrong that would be great. -Thanks in advance

**Comment by alcatrazEscapee** [comment]
> here are no rock on the ground

Because the 1.16.3 version was released before adding world gen was possible in forge without a huge pile of gross.

> As well as I can't break grass, sand, or dirt

Ya that's what the mod does. No tree punching, or no punching any of the other things too. Punching bad.

**Comment by YeetusShlumpedYT** [comment]
what about breaking stone and getting the pebbles.
I've tried the config and still cant get the loose rocks from stone.
