### ISSUE TITLE
Can't collect plant fiber in newest version.

### ISSUE THREAD

**Issue by chickenkeiv50** [alcatrazEscapee/no-tree-punching#135]
As title states, using a flint knife and destroying any grass or flower will not drop plant fiber.

Edit : To be clear, I did test this in a superflat world, spawned in lots of grass and went to town, after 8 flint knives I recieved 0 plant fiber.

**Comment by Grotts** [comment]
I also noticed this, however, I noticed tall grass seems to work correctly.

**Comment by alcatrazEscapee** [comment]
> newest version

What mod version and minecraft version?

**Comment by ghost** [comment]
> > newest version
> 
> What mod version and minecraft version?

it's 1.16.3 version of the mod. i tried this in my modpack but it doesnt work.

**Comment by ekiplier** [comment]
the same has been happening to me. There seems to be no way of obtaining plant fiber (unlike some cases I've seen commented here where people are able to obtain it from tall grass), and the stick drops from leaves are abnormally rare.
I'm using Forge-34.1.42
notreepunching-forge-1.16.3-4.0.1.jar
