### ISSUE TITLE
Config Questions

### ISSUE THREAD

**Issue by YeetusShlumpedYT** [alcatrazEscapee/no-tree-punching#136]
in the config there is a section that allows you to keep certain blocks always breakable. However by changing theses settings it shoed no effect in game. So I was wondering if this was something that you could fix. 
Thanks in advance, 

-YeetusShlumped

**Comment by alcatrazEscapee** [comment]
As you haven't provided any relavant version information, I will assume you're using anything >= 1.12 (as I am not supporting anything else). As outlined in the [wiki](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking#configuration), anything you want to be always breakable or always drops will require adding to a tag. If you don't know what those are, please consult the documentation on [creating a data pack](https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack) and [tags](https://minecraft.gamepedia.com/Tag).
