### ISSUE TITLE
unbreakable blocks doesn't make sense.

### ISSUE THREAD

**Issue by ghost** [alcatrazEscapee/no-tree-punching#137]
When you start the game, God forbid that you fall into like a dirt lake, because you will never be able to break that dirt, at least by default. It doesn't make sense at all, blocks like dirt and stone and wood should be breakable with hands by default, and not drop anything. I saw there are server config option like noMiningWithoutCorrectTool, is there a way to change them in the singleplayer?

**Comment by alcatrazEscapee** [comment]
> server config option [...] is there a way to change them in the singleplayer?

Yes. Forge **server** configs are simply per world, syncable configs. Copying from another explanation:

> NTP uses a server config, which is found inside the world folder (.minecraft/saves/<world>/serverconfig/notreepunching-server.toml)
> This particular type of config,
> - is unique per world
> - is synchronized from servers -> clients
> - can be overriden (i.e. for the purpose of not having to edit the config every time you create a world) by the defaultconfigs folder - any server configs found under .minecraft/defaultconfigs will be copied to any new worlds when created (overriding the mod defaults)

I do not plan to change the defaults as they effectively do what it says on the tin.
