### ISSUE TITLE
NO vanilla wooden or stone tools

### ISSUE THREAD

**Issue by AL3X08** [alcatrazEscapee/no-tree-punching#139]
im playing a custom mod profile and i download the most recent file for no tree punching and there's no wooden of stone vanilla tools its most likely a bug but i would like to know how to fix this

**Comment by alcatrazEscapee** [comment]
See [the wiki](https://github.com/alcatrazEscapee/no-tree-punching/wiki). Namely, this line:

> - Vanilla recipes for wooden and stone tools have been removed.
