### ISSUE TITLE
No way to obtain plant fiber

### ISSUE THREAD

**Issue by ekiplier** [alcatrazEscapee/no-tree-punching#145]
Unlike some cases I've seen reported here, I can't obtain plant fiber by ANY means. No matter what tools I use or what blocks I break, it seems impossible to harvest them. Also, I believe stick drops from leaves are much rarer than they should be, even compared to vanilla's rng.
I'm using forge-34.1.42
notreepunching-forge-1.16.3-4.0.1.jar

Here's the logs file:
[latest.log](https://github.com/alcatrazEscapee/no-tree-punching/files/5799336/latest.log)

**Comment by alcatrazEscapee** [comment]
- I don't touch stick drops from leaves in any way. "I believe they are rarer than they should be", as a statement of fact is sorely lacking.
- The other issue you mentioned was fixed already, in the version you're not using.
- You're using a whole host of other mods which one of which probably overrides the same loot table. This would require overriding ore re-ordering the mods resources.
