### ISSUE TITLE
enableLooseRocksWorldGen = false still generates rocks

### ISSUE THREAD

**Issue by tylerius** [alcatrazEscapee/no-tree-punching#146]
title says it all, I have 100% saved the config, restarted the game, and generated a new world. I've attached a list of mods just in case it helps. 

[list.txt](https://github.com/alcatrazEscapee/no-tree-punching/files/5820263/list.txt)

**Comment by alcatrazEscapee** [comment]
lol, helps if you actually check the config value when generating rocks 🤦

**Comment by tylerius** [comment]
Hm. maybe I don't understand what this does. Re-reading the comment in the file it seems like you intend for rocks to either be put into a wider arrange of biomes even added by mods or not? Originally I was under the impression that this disabled loose rocks completely in case of a compatibility issue.

**Comment by rckymtnrfc** [comment]
I'm still seeing this bug.  I've set the config to not generate loose rocks but they are appearing everywhere in world.

**Comment by alcatrazEscapee** [comment]
Yes... because I haven't gotten around to fixing it... so it's not fixed.... 😆

**Comment by rckymtnrfc** [comment]
Ah, sorry.  Didn't mean to pester you.  I just really want to use this mob but don't like the little rocks all over.  I'll be patient.  =)
