### ISSUE TITLE
Suggestion: Tag the cobblestone variants for practical use

### ISSUE THREAD

**Issue by alexanderkw** [alcatrazEscapee/no-tree-punching#147]
Andesite, granite, and diorite cobblestone can only be used as decoration currently. As cobblestone variants it would make sense for them to be valid materials for furnaces etc.

This can be partially achieved in 1.16 with the `minecraft:stone_tool_materials tag` for the block item, or alternatively with the relevant forge tag for cobblestone.

**Comment by alcatrazEscapee** [comment]
Hmm. It seems I had already tagged them `cobblestone` but under the `notreepunching` namespace. That probably can just be added to the relavant forge + vanilla tool tags.
