### ISSUE TITLE
Two Issues!

### ISSUE THREAD

**Issue by thedeerirty** [alcatrazEscapee/no-tree-punching#150]
1. Has this dropped Biome's O Plenty support? I'm finally updating from crusty 1.12 to 1.16 where I was used to it working.

2. I think Ice and Fire causes a conflict with sticks dropping from leaves

**Comment by alcatrazEscapee** [comment]
Then make two issues.
re 1. "support" is "add the recipes yourself via a datapack". It's not automatic anymore as that's not possible with datapacks.
re 2. that's a vanilla feature, idk why you're reporting that to me.
