### ISSUE TITLE
Crash with `Tag .. used before it was bound` in SMP

### ISSUE THREAD

**Issue by Maekuno** [alcatrazEscapee/no-tree-punching#151]
Hi so the thing is that I can use the mod in my solo game, I installed it on my private server, I join everything is fine until I punch a block, my game crash, not the server. 
Here is the error I get in the launcher : 
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Tag notreepunching:always_drops used before it was bound
Code de sortie : -1
[crash-2021-01-27_17.29.14-client.txt](https://github.com/alcatrazEscapee/no-tree-punching/files/5881637/crash-2021-01-27_17.29.14-client.txt)

**Comment by alcatrazEscapee** [comment]
Interesting. Have you removed that tag via a datapack?

Edit: I cannot reproduce. Everything about this error indicates the tag was not present on one side, which is not allowed. More information is required in order to be able to diagnose this.

**Comment by Maekuno** [comment]
Ok I figured it out and it was my fault i was nlt launching the forge
server ! It launched it on a vanilla server ^^' Thank you for responding
and by the way I really love your mod you did a great work on it 😁😁
