### ISSUE TITLE
Valhelsia Structures with this mod

### ISSUE THREAD

**Issue by dwiantlake** [alcatrazEscapee/no-tree-punching#152]
Whenever I tryna make a Plank from any log other than Oak with any axe, it can't be done
It only shows the valhelsia structures recipe which was a "[any wood type] Post"

**Comment by alcatrazEscapee** [comment]
You haven't described an issue? If you have other mods that alter crafting recipes, crafting recipes may be altered. Feel free to make a [datapack](https://minecraft.gamepedia.com/Data_Pack) to resolve recipe conflicts.

That, or if you think this is still an issue with the mod, please describe the exact issue in detail, including what you're expecting to happen and where the issue occured.
