### ISSUE TITLE
Make a better config file?

### ISSUE THREAD

**Issue by JaddotWuzHere** [alcatrazEscapee/no-tree-punching#154]
I figured it would be great if you made a config file like the ones in pre 1.12.2 for 1.16? When I downloaded this mod for 1.16 I wanted to configure some of the mods, like adding back wooden/stone tools, or increase flint/fiber drop chances, etc, but I couldn't find anything besides a 'naturally generate stones' option in the config. It would be amazing if you added more options. This really isn't much of an issue, but I think it would be a great addition to the mod, and have more flexibility over how all the mechanics work. 
Thanks!

**Comment by alcatrazEscapee** [comment]
There is one. Common config has world gen options. Server config has all other options. Almost all options you just mentioned already exist.

**Comment by JaddotWuzHere** [comment]
Where is the server config?

**Comment by alcatrazEscapee** [comment]
[Copied from an FAQ on my discord](https://gist.github.com/alcatrazEscapee/93bfd871f114437823ae7a673d6b85b3)
