### ISSUE TITLE
Investigate multiple harvest tools for ones where the default tool is non-ovbious

### ISSUE THREAD

**Issue by alcatrazEscapee** [alcatrazEscapee/no-tree-punching#157]
The most common case is that blocks of material plant get classified as using the axe tool type, despite most assuming either breaking by hand, shears, or knife/sword. Main issue is that changing directly would be a rather difficult (and potentially problematic) break from vanilla behavior. Support for additional tool/material combinations, ideally in both an automatic and configurable manner would be useful.

**Comment by dchieh222** [comment]
This is a pretty severe issue, verging to making the game nonplayable for me. Does this potentially break interaction with other craft/autoharvest mods?
