### ISSUE TITLE
Recipe Bug

### ISSUE THREAD

**Issue by The-Brandolorian** [alcatrazEscapee/no-tree-punching#159]
When I craft Oak Planks using an axe, it consumes the axe. It does not do this with Spruce, can test other wood types if need.
I'm on my personal pack - https://www.curseforge.com/minecraft/modpacks/creations-adventures
I've made a little bit of compat recipes but nothing that should have affected the oak recipe.

**Comment by The-Brandolorian** [comment]
It appears this only happens with an axe I used Kubejs to add the Weak_saws tag too and only with oak wood

**Comment by alcatrazEscapee** [comment]
Can you reproduce this with a default NTP install?

**Comment by tikiman141** [comment]
when i combine the flint hatchet and a log, nothing happens

**Comment by The-Brandolorian** [comment]
Sorry! did not see this reply. I'm not sure if this is a thing anymore, going to close the thread.
