### ISSUE TITLE
Crafttweaker support

### ISSUE THREAD

**Issue by timothygremlin** [alcatrazEscapee/no-tree-punching#160]
Hi, is there a script documentation for crafttweaker support somewhere? I want to add some recipes to knife cutting but can't seem to find anything on that. If anybody knows anything please help.

Not really an issue, more a question :)

**Comment by alcatrazEscapee** [comment]
It is in the github wiki.

However, due to my only being able to support the latest, the github wiki has been updated to 1.16.x. If you wish to view 1.12.x documentation, you will need to browse the history locally as github only hosts the most recent update.
