### ISSUE TITLE
Lack of Config Features

### ISSUE THREAD

**Issue by TechnoMage303** [alcatrazEscapee/no-tree-punching#161]
I would like to be able to disable or remove mattocks and other items or blocks from the game via the config file. I'm trying to make a modpack (won't be published) for my friends and I to play on and am currently waiting for TC (Tinkers Construct) to update which adds the mattock. If not no big issue, other users would likely find this helpful as well with the added options.

**Comment by alcatrazEscapee** [comment]
No. Not happening. If you don't want to obtain items remove the recipes for them via datapack.
