### ISSUE TITLE
Breaking andesite and other stone types

### ISSUE THREAD

**Issue by ChubbsWasTaken** [alcatrazEscapee/no-tree-punching#164]
when i break andesite and or any other stone types it drops the block instead of loose rocks, no config for it exists (or if it does i didnt see it)

**Comment by ChubbsWasTaken** [comment]
found the config thing. its set to true. no effect

**Comment by alcatrazEscapee** [comment]
1.12 is not supported. If this is not 1.12, then block drops are freely editable via a datapack, and NTP does not change stone drops, nor any config for it exists.
