### ISSUE TITLE
Game crashes when using the Small Ceramic Vessel

### ISSUE THREAD

**Issue by fivedollarlamp** [alcatrazEscapee/no-tree-punching#165]
Whenever I open the Small Ceramic Vessel and click on an item in my inventory, the game crashes.

**Comment by alcatrazEscapee** [comment]
What minecraft version? And if it crashes, please provide the crash report or full log file (`latest.log` in the logs folder).

**Comment by alcatrazEscapee** [comment]
Can't reproduce, can't do anything without more information.
