### ISSUE TITLE
Unbreakable leaves

### ISSUE THREAD

**Issue by ChubbsWasTaken** [alcatrazEscapee/no-tree-punching#166]
when my friend joins my world and attempts to break either the log or leaves of Dynamic Trees, the wood is unbreakable and the leaves break instantly, dont drop anything and respawn like a world-guard.

(no world guard mod or plugin exists on our world)

**Comment by alcatrazEscapee** [comment]
1.12 is not supported. And this sounds like an issue you might want to deal with dynamic trees for.
