### ISSUE TITLE
[question] which type of blocks are prevented from hand harvesting

### ISSUE THREAD

**Issue by lyssar** [alcatrazEscapee/no-tree-punching#168]
Hey,
I noticed that trees from Biomes O' Plenty or Oh The Biomes You'll Go can be harvested by hand and the question raised in my head: how to you prevent vanilla stuff from be harvested or produced through the axe?
Can I enhance this by myself through config?

Cheers and thank you for anwering,
lys.

**Comment by alcatrazEscapee** [comment]
All the mechanical changes are documented in [the relevant wiki article on "Block Breaking"](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking). Including possible configuration options both through config, and tags.

As far as how this is done, NTP makes several edits to block and item tool properties, all documented in [HarvestBlockHandler](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.16.x/src/main/java/com/alcatrazescapee/notreepunching/util/HarvestBlockHandler.java)

**Comment by rckymtnrfc** [comment]
Is there any way to customize certain blocks.

I just discovered, as lyssar did, that BYG logs can't be broken with an empty hand but if I'm holding any item, it breaks and drops.  There are other items, like Overgrown Dacite that can not be broken normally (when NTP isn't installed) but once I add NTP, I can break this block bare handed and I get the block.

Unfortunately it breaks a big part of your mod when players can get logs without having to get the correct tools first.

I should mention I have these settings in my config.  Normal vanilla logs respect these rules but BYG logs do not.
noMiningWithoutCorrectTool = true
noBlockDropsWithoutCorrectTool = true

**Comment by alcatrazEscapee** [comment]
Usually this indicates an issue with the other mod (and in this case I have just spoken with the author of BYG about logs in particular). There is no way to modify block tool types, or tool harvest types via datapack.

*That said* there may be ways to skirt this requirement - or at least, improve default tool assignments. And one thing you did say there

>  can't be broken with an empty hand but if I'm holding any item, it breaks and drops.

sounds like it may be an issue for NTP.
