### ISSUE TITLE
Wood can't be cut.

### ISSUE THREAD

**Issue by ZephyraNF** [alcatrazEscapee/no-tree-punching#170]
When putting logs and axes into a crafting table, only flint axes can cut them into sticks and planks.

**Comment by alcatrazEscapee** [comment]
This is intended behavior - saws can be used for both crafting, and as a full radio (flint axe belongs to the `weak_saws` tag and only gives 2 planks/log.

However, you make a good point in that there's no reason for other axes not to also be added to the same tag, provided they're producing less than saws to compensate.
