### ISSUE TITLE
[Suggestion] Netherite versions of tools

### ISSUE THREAD

**Issue by van-riper** [alcatrazEscapee/no-tree-punching#172]
Don't know if this is too much to ask for, but I noticed that there are no Netherite versions of the Knife, Saw, Mattock. Is there planned integration for this?

**Comment by alcatrazEscapee** [comment]
Ya I realized this as well :P

**Comment by van-riper** [comment]
Also, there doesn't seem to be integration for the soul campfire either, just pointing out.
