### ISSUE TITLE
1.12.2 version doesnt drop sticks when leaves decay themselves.

### ISSUE THREAD

**Issue by AikaBack** [alcatrazEscapee/no-tree-punching#174]
I have fast leaf decay, so if I don't carefully pick which leaves I destroy, I might get all leaves dissapear with no sticks dropped by destroying few leaf blocks. Is there a way for sticks to be dropped not only though manually punching leaves?

**Comment by alcatrazEscapee** [comment]
Not supporting 1.12, sorry.
