### ISSUE TITLE
1.16.4 Versions doesn't drop sticks

### ISSUE THREAD

**Issue by Ravin26** [alcatrazEscapee/no-tree-punching#175]
When I break leaves in the 1.16.4 version of this mod the leaves don't drop sticks.

**Comment by alcatrazEscapee** [comment]
Cool. Since this is a vanilla feature that has nothing to do with NTP, why don't you, if you think you can reproduce this, go make an issue on the vanilla issue tracker instead?

In short... yes they do... and NTP does nothing to touch that.
