### ISSUE TITLE
Valhelsia Structures recipe conflict with Notreepunching mod (1.16.5)

### ISSUE THREAD

**Issue by dkaarvand** [alcatrazEscapee/no-tree-punching#176]
Hi

I'm running several mods, where the two distinctive ones that I think are causing some trouble are;

- Notreepunching
- Valhelsia Core, Valhelsia Structures

[This](https://i.imgur.com/HsgMF83.png) is what happens when I try to make wooden planks with a saw. Also in [any](https://i.imgur.com/E1d2mLO.png) order gives the same results. Is there a quick workaround to fix this? I tried using CraftTweaker to remove recipes, problem is, it only removes the recipes for all the posts items that were added by Valhelsia Structures - but you can still craft them without the recipe

**Comment by alcatrazEscapee** [comment]
So this sounds like a recipe conflict. There's not much specific I can do, nor want to do, to, for example, force NTP's recipes to take priority as that's just a bit dickish.

What you can do, is write a [DataPack](https://minecraft.fandom.com/wiki/Data_Pack) which either overrides, removes, or resolves these recipe conflicts, picking what recipes you'd like to exist and changing them in such a way that they have no conflicts.

If you want to see NTP's recipes, they are all [on github](https://github.com/alcatrazEscapee/no-tree-punching/tree/1.16.x/src/main/resources/data/notreepunching/recipes).

**Comment by V972** [comment]
Another solution is to use [Polymorth](https://www.curseforge.com/minecraft/mc-mods/polymorph), which enables to choose outcome of colliding recipes.
