### ISSUE TITLE
Charcoal Forge Suggestion

### ISSUE THREAD

**Issue by Lordician** [alcatrazEscapee/no-tree-punching#18]
I have a suggestion for the charcoal forge. While i know the charcoal forge is still work in progress because bellows are still coming, i also would want to see it being possible to create multiple charcoal forges within one stone ring.
So for example a 2x2 charcoal pit with stone bricks surrounding it being valid.
The fuel you put in would be distributed over the different connected piles and they would all be lit if you light one on fire.

**Comment by alcatrazEscapee** [comment]
That sounds interesting. However I'm having trouble seeing what the added advantage of this would be. The charcoal forge is thematically not meant to replace the furnace, but rather be a early game alternative. As far as efficiency / speed I think that is better suited to a different device. But I'm curious: what would you have a larger forge do that a small one can't?

**Comment by Lordician** [comment]
It is mostly aesthetics.
And having multiple close to each other brings efficiency in terms of how much space multiple forges would cost.
I get that the forge is supposed to be an alternative (even though by default it replaces the furnaces ore smelting?) but even for that purpose efficiency will be appreciated by some.
But all in all i made the suggestion mostly for aesthetic purposes.

**Comment by alcatrazEscapee** [comment]
Just musing here: I could probably pretty easily make forges work side by side, light in sync, that sort of thing. The difficult thing would be to make them all share an inventory. I would have to do some major rewrite to get that to happen. Would it be strange if each charcoal pit had its own inventory / cook timer rather than them being grouped together?

**Comment by Lordician** [comment]
Each having their own inventory and cook time is perfectly fine, i was mostly talking about syncing the charcoal level and spreading charcoal you put in over every forge that connects. If that is not possible, that is not the end of the world.
It would be nice but just being able to make forges side by side would be great already.

**Comment by Lordician** [comment]
I played with it a little, seems fine as is.
The highest stack mechanic seems to work good so far and stabilizes the piles nicely.
Thanks a lot!
