### ISSUE TITLE
Wood doesn't drop planks

### ISSUE THREAD

**Issue by Xajfaj** [alcatrazEscapee/no-tree-punching#181]
When I right click with axe on wood it doesn't drop planks, but it's skinning the tree. 
game version: 1.16.5
mod version: 1.16.5-4.1.3 ( newest )

**Comment by alcatrazEscapee** [comment]
Yes, that's intentional. See: vanilla.

If you are trying to create wood planks, use the crafting recipe. See in either the recipe book, or using JEI (the mod).
