### ISSUE TITLE
[NTP for Mc 1.12.2] Compatibility issue with MachineMuse's Modular Powersuits

### ISSUE THREAD

**Issue by Frankaos333** [alcatrazEscapee/no-tree-punching#182]
As per title, I found NTP isn't compatible with MachineMuse's Modular Powersuits (a mod which in turn requires another mod, Numina, I have v1.0.46 of the former and v1.0.38 of the latter) as wood and stone blocks won't drop if you break it with the tool from that mod.
How to test the issue:
- Install NTP (and turn on the setting that makes it so blocks don't drop if you mine them without a tool)
- Install the two mods mentioned above (along with CoFH's Thermal Expansion, which helps with testing)
- Give yourself the power fist item (id: "powersuits:power_fist") and the power armor tinker table (id: "powersuits:tinkertable")
- Place the table and open it's GUI
- Select the power fist on the left, a list of icons should pop up
- Select any one of the upper four icons (the ones labeled as "battery") and install it by clicking "install" on the bottom of the GUI
- Select the icon labeled "axe" and install it as above, a yellow bar labeled "overclock" should pop out to the right, set it to the max value
- Do the same for the icon labeled "pickaxe"
- Charge the powerfist using the energetic infuser from Thermal Expansion, hooked up to an RF power source
- The power fist should now break wood and stone blocks as if it were a very powerful axe or pickaxe, but NTP doesn't recognize it as such and thus the blocks won't drop
- When turning off the relevant config in NTP (the enableBreakingChanges boolean flag), blocks will drop again

**Comment by alcatrazEscapee** [comment]
Not supporting 1.12 anymore, sorry.

Apologies for telling you to submit this issue before confirming what version it was for, my bad.
