### ISSUE TITLE
BYG Compatibility

### ISSUE THREAD

**Issue by TheLonelyExplorer** [alcatrazEscapee/no-tree-punching#189]
The wood types BYG adds can be converted into planks without any tools. I'm not very experienced in modding and can't use craft tweaker or anything like that to fix the recipe issue.

**Comment by alcatrazEscapee** [comment]
Duplicate of #127

And, WIP compatibility is already present in dev explicitly for BYG.

And and:

> can't use craft tweaker or anything like that

Shame. Make a datapack.
