### ISSUE TITLE
Suggestion: Integrate fire pit with camp fires, etc from Tough as Nails

### ISSUE THREAD

**Issue by Stormwind99** [alcatrazEscapee/no-tree-punching#19]
No Tree Punching and Tough As Nails are logical companions - support for them together would be great.

Examples: 
* Merge or make equivalent NTP's fire pit and [TAN's camp fire](https://github.com/Glitchfiend/ToughAsNails/wiki/Campfire) (including heat)
* Make NTP's fire starter work on TAN's camp fire, etc

I wonder if there is a generic Forge support or Minecraft tag for "things that ignite other things" and "things that burn" that could be used.

Thanks for the fun mod!

**Comment by alcatrazEscapee** [comment]
Closing as I'm realistically never going to get around to doing this

**Comment by wilbowma** [comment]
FWIW, I'm using the following Craft Tweaker script to workaround this compatibility issue:

```
import crafttweaker.item.IItemCondition;

val flintnsteel = <minecraft:flint_and_steel>;
flintnsteel.maxDamage = 10;
flintnsteel.displayName = "Fire Starter";
flintnsteel.withTag({fire_starter: true});
recipes.addShapeless("(Weak) Flint and Steel", flintnsteel, [<notreepunching:fire_starter>],
                    function(out, ins, cinfo){
                        return out;
                    }, null);
```

This allows you craft a low-durability flint and steel from a fire starter. It's not a great alternative, but it looks like Tough as Nails hard codes the flint and steel item, so it's not easy to make compatible.
https://github.com/Glitchfiend/ToughAsNails/blob/4417d9aaf8d1556ba9a629724a9829b4d22a0613/src/main/java/toughasnails/block/BlockTANCampfire.java#L161
