### ISSUE TITLE
Game won't launch using Quark or Farmer's Delight

### ISSUE THREAD

**Issue by wenlfs** [alcatrazEscapee/no-tree-punching#195]
Using the version 4.2.1 won't launch when using the newer versions of Quark and Farmer's delight. As you can see the versions of I`m using are in the picture.

![image](https://user-images.githubusercontent.com/41978516/125727135-acc15e0c-3ed5-4272-9d12-6859e9fba702.png)

Thank you.

**Comment by alcatrazEscapee** [comment]
Excuse me what?

Attach the full crashlog please.

**Comment by wenlfs** [comment]
Here: https://pastebin.pl/view/8f158347

**Comment by alcatrazEscapee** [comment]
*insert old man yelling at cloud*

Apparently optional mod dependencies have mandatory `versionRange` requirements despite not listing them as mandatory since https://github.com/MinecraftForge/MinecraftForge/pull/7710... forge please.

**Comment by alcatrazEscapee** [comment]
https://github.com/alcatrazEscapee/no-tree-punching/commit/157336fdd6f47b8f20889e23a63ab67c1f6f0d46
