### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by Topside08** [alcatrazEscapee/no-tree-punching#197]
when interacting with storage drawers and I imagine any other wooden block that you hit to use you take damage a blacklist for blocks like this would be great alternatively the damage could happen when the block actually starts to break instead of on the first hit

**Comment by alcatrazEscapee** [comment]
This mod does not deal damage when you start to break things. You can already add blocks that you want to not require a tool to the relevant tag, as outlined in the [wiki](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking#configuration).
