### ISSUE TITLE
1.17 Plan

### ISSUE THREAD

**Issue by alcatrazEscapee** [alcatrazEscapee/no-tree-punching#200]
### Overview

- 1.17 has a lot of nice incentives to update for.
- Forge is unstable, missing key features, and generally making it very painful to update.
- Plan is to keep maintaining 1.16.5 until 1.17, or a future version, is in a usable state.

Notable:

- No mixin (yet). Only use can be replaced with ATs in 1.16.
  - Mixin and Mixin gradle are in snapshots. They can be used in dev, with mixin bootstrap in production (for now).
- Mojang decided tool requiring blocks should now use tags.
- Despite all the above, `BlockBehavior#requiresCorrectToolForDrops` still exists... so there's hope this is as simple as it is in 1.16.
- Forge PRs:
  - https://github.com/MinecraftForge/MinecraftForge/pull/7970
  - https://github.com/MinecraftForge/MinecraftForge/pull/8024

**Comment by TheeMrCheeky** [comment]
I feel 1.18 will end up being the sweet spot to update to! Since 1.19 will be start of wild update and 1.17 was start of caves and cliffs. Keep up the good work though!! Great mod!

**Comment by alcatrazEscapee** [comment]
https://github.com/alcatrazEscapee/no-tree-punching/releases/tag/v5.0.0
