### ISSUE TITLE
Better default biomes compatibility

### ISSUE THREAD

**Issue by YejiYeah** [alcatrazEscapee/no-tree-punching#202]
Is this mod compatible with Better default biomes mod?,

I am using it and I am able to craft the planks without using the axe or saw

Thank you,
Best regards
Sarah

**Comment by alcatrazEscapee** [comment]
Duplicate of #127

**Comment by alcatrazEscapee** [comment]
I suggest reading the linked issue as it will tell you

- Why NTP can't do this automatically. (and so if I were to, I'd have to add compatibility for *every single mod* that gets requested).
- How you can do it yourself it you'd like.
