### ISSUE TITLE
[Suggestion] Compatibility with Origins

### ISSUE THREAD

**Issue by ekiplier** [alcatrazEscapee/no-tree-punching#203]
I think this is more of a question disguised as a suggestion: Is it possible to make NTP compatible with Origins for Forge? I want to leave noMiningWithoutCorrectTool true, but there's an origin (shulk) that should be able to break stone blocks with their bare hands. Could this be a feature?

**Comment by alcatrazEscapee** [comment]
This should already be possible, see the wiki on existing configuration options for block breaking.

https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking

**Comment by ekiplier** [comment]
So do I add the Tag to stone blocks?
