### ISSUE TITLE
Tetra Tools

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [alcatrazEscapee/no-tree-punching#205]
![2021-09-26_11 42 43](https://user-images.githubusercontent.com/6131437/134817566-0779d45e-b697-4010-9d72-5313f4fec35c.png)
No Tree Punching and Tetra have little to no integration.  I am unable to use Tetra tools to cut cactus.  I might also be unable to use other tools like the picks, axes, shovels, mattocks, and other Tetra tools for breaking blocks and block-based things.  I don't know which mod would need to fix it, but I just thought it was important to mention.  The version of NTP that I am using is 4.2.3 and the version of Tetra I am using is 3.17 with mGUI version 3.3.  I'm also using Tetra Pak and Tetranomicon.  I'm not sure if the addon mods will matter in this case, because the tools from the addons should be more or less in the same state as the main mods tools.

**Comment by alcatrazEscapee** [comment]
Hmm. I'd have to look into it and test more thoroughly to see what's actually going on, my brief peruse of the Tetra code base is not showing anything obvious that would be the cause (that would be an issue with Tetra).

**Comment by PliskintheSaltyFork** [comment]
I added a picture to show what is not working.

**Comment by CatAndPaste** [comment]
I have a problem with Tetra tools as well, but in my case double-headed modular tools can't break any leaves in multiplayer server. Instead of being broken, leaves disappear and player can stuck into them. On right click or update of nearby blocks, they appear again. It looks like desync problem but only happens when leaves are broken with Tetra tools.

**Comment by alcatrazEscapee** [comment]
Sorry, I'm not supporting 1.16.x anymore - if the issue persists in the latest version (1.18.x), please mention or open a new issue.

**Comment by Proxwian** [comment]
Issue is persist in 1.18.2. I cannot break blocks with tetra tools
