### ISSUE TITLE
Project Vibrant Journeys compatibility

### ISSUE THREAD

**Issue by coldloaded** [alcatrazEscapee/no-tree-punching#206]
These two mods (No tree punching and Project Vibrant Journeys) work perfectly together, it seems like they were created to complement each other, and yet there is no compatibility between them. It would be nice to see the possibility of creating fibers using cattail and sea grass (from pvj) in this mod.

**Comment by alcatrazEscapee** [comment]
> These two mods (No tree punching and Project Vibrant Journeys) work perfectly together, it seems like they were created to complement each other, and yet there is no compatibility between them.

Aside from the aforementioned crafting recipe addition, I'm curious if you have any idea of what compatibility you'd envision between the two mods? As I've heard of Project Vibrant Journeys before, and that's about the extent of my knowledge of it.

**Comment by coldloaded** [comment]
> 
> 
> > These two mods (No tree punching and Project Vibrant Journeys) work perfectly together, it seems like they were created to complement each other, and yet there is no compatibility between them.
> 
> Aside from the aforementioned crafting recipe addition, I'm curious if you have any idea of what compatibility you'd envision between the two mods? As I've heard of Project Vibrant Journeys before, and that's about the extent of my knowledge of it.

It seems that there is nothing much to come up with, only recipes for obtaining fiber from different types of grass. 
However, I have in mind some other mod that also includes early game content, and which could have a bit more complex compatibility with ntp. I can launch a new thread for this.
