### ISSUE TITLE
[Feature Request 1.16.5] Ability to disable NoTreePunching Campfire features

### ISSUE THREAD

**Issue by p1ut0nium-git** [alcatrazEscapee/no-tree-punching#208]
I use other mods that limit the burn length time of campfires. They must be refueled and relit, but it seems that No Tree Punching conflicts with this. Once a campfire it lit, it seem to last forever.

Can you either add this feature (limit burn length time based upon how much fuel is added like coal) or...
Disable messing with campfires all together.

**Comment by alcatrazEscapee** [comment]
What are you talking about... you mean the vanilla campfire? The one that has no fuel at all?

I don't touch vanilla campfires, I simply change the way to create them.

**Comment by p1ut0nium-git** [comment]
Odd. Ok then nevermind. It must be something else causing the issue.
