### ISSUE TITLE
Beta Feedback - Dust to Ingots

### ISSUE THREAD

**Issue by Lordician** [alcatrazEscapee/no-tree-punching#21]
Not really a big issue, but i think it would make sense if dust (like copper, tin and iron) should be able to put in the forge to melt into ingots.

**Comment by alcatrazEscapee** [comment]
AFAIK I added this... See 3864a31a6f5fafe46d5ddf343d1a8dfdbadb5503 Do the recipes not show up in JEI or are they non-functional?

**Comment by Lordician** [comment]
Uhm... Ignore this bug report, i forgot i removed all the ingot output recipes from the forge (because i wanted to replace them with nuggets, which works great btw).
I did not think of this when i played with the dust.
Sorry i will be sure to test things in a clean environment next time before i report an issue.
