### ISSUE TITLE
Suggestion: worked clay drops clay balls at end of cycle

### ISSUE THREAD

**Issue by inkdear** [alcatrazEscapee/no-tree-punching#210]
Just thought it'd be nice if the sequence of sculpted clay blocks ended with some clay ball items dropping on the ground (equivalent to breaking a clay block) rather than disappearing completely. ^^

**Comment by alcatrazEscapee** [comment]
[Change the loot table of the last clay block if you so desire](https://minecraft.fandom.com/wiki/Loot_table). I don't see a compelling reason for this to be part of NTP, pottery is already cheap as is feasible.

**Comment by inkdear** [comment]
Sorry, I wasn't familiar enough with newer versions' block loot table editing capabilities.
