### ISSUE TITLE
Suggestion: More config options

### ISSUE THREAD

**Issue by inkdear** [alcatrazEscapee/no-tree-punching#212]
This may sound, uh... odd, but it'd be great to have the option to disable the mod's central theme and return block breaking to normal. This is mostly because the pottery sculpting and flint knapping aspects are really useful as modpack utilities, even with normal block breaking (and the mod's progression actually remains the same even with normal block breaking, since you can't progress without maklng the flint tools anyway.)

I would also suggest a config to disable the alternate planks/logs recipes, though that can be solved by editing the jsons directly I think (only just upgraded from 1.12, still figuring datapack stuff out lol)

The ability to choose the frequency of surface rock generation could also be handy, and super-situationally, possibly the ability to add unfired clay blocks to the clay tool sequence.

**Comment by alcatrazEscapee** [comment]
> This may sound, uh... odd, but it'd be great to have the option to disable the mod's central theme and return block breaking to normal.

[Already Possible](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking#configuration)

> I would also suggest a config to disable the alternate planks/logs recipes, though that can be solved by editing the jsons directly

Yes... yes it can.

> The ability to choose the frequency of surface rock generation

While the frequency is not, the [entire feature is](https://github.com/alcatrazEscapee/no-tree-punching/wiki/WorldGeneration#configuration).

> and super-situationally, possibly the ability to add unfired clay blocks to the clay tool sequence.

See response to #211

**Comment by inkdear** [comment]
> Already Possible

Ah. Um. This explains a few things, but I only seem to have the notreepunching common config generating in my config folder - I can only see the file with the ability to disable rocks spawning. This again may be down to stupidity inherited from coming to 1.16 a few days ago from 1.12, but I can't find a server config for the mod anywhere in my .minecraft other than in individual save folders, and no answers from searching, is it missing or is there really no 'master copy' and you have to edit it per world each time?

**Comment by alcatrazEscapee** [comment]
https://gist.github.com/alcatrazEscapee/93bfd871f114437823ae7a673d6b85b3

**Comment by inkdear** [comment]
Thank you so much. Sorry to have been bothersome.
