### ISSUE TITLE
Decorations spawning on top of pebbles

### ISSUE THREAD

**Issue by Krampus69** [alcatrazEscapee/no-tree-punching#215]
Hello 👋 
I sometimes see ByG or project vibrant journeys ground blocks spawning on top of the no tree punching rock blocks.
I asked them and they said that the problem was how the rock was set, so apparently there is a way to set the properties of this block to forbid anything spawning on top of it.

Here is a picture for example : 
![2021-12-20_18 37 48](https://user-images.githubusercontent.com/81943963/147353411-0e6164d1-eb49-47c3-bd2f-2775f24eee29.png)

That's a vibrant journeys plant spawning on top of this rock.

I'm using minecraft 1.16.5
Forge 36.2.9
notreepunching-forge-1.16.5-4.2.3

**Comment by alcatrazEscapee** [comment]
I don't quite understand how this is occurring. There's two scenarios:

1. Loose rocks are placing on top of existing features - this shouldn't be possible, loose rocks already explicitly check and will only replace blocks that return `true` to `BlockState#isAir`, and will only place on blocks explicitly whitelisted in the `#notreepunching:loose_rock_placeable_on` tag.
2. Other features are placing on top of loose rocks - The other feature should do adequate checks (which to the extent I can see, for instance, [PVJ already does](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/e5ba393a012c3bfb9bade13d87fb458fc961e9cc/src/main/java/projectvibrantjourneys/common/world/features/blockplacers/RocksBlockPlacer.java#L35) - they check if the collision shape is a full block, and if the block has a solid render (a bit of an odd check, but NTP returns true to both of those. And I don't see what properties my block is missing that would incorrectly mark it as "solid ground".

**Comment by Krampus69** [comment]
I have no idea either why this is occuring. An easy way to test it out is to download ByG and 
/locatebiome byg:cherry_blossom_forest

There you can find white cherry foliage on the ground, they will spawn on top of pebbles and float weirdly just like this

![2022-05-10_13 24 30](https://user-images.githubusercontent.com/81943963/167617991-a83d246a-2761-4563-a165-14744e83adf7.png)

The screenshot was taken on 1.16.5
byg-1.3.5
notreepunching-forge-1.16.5-4.3.0
Forge 36.2.34

If that can help...This biome in particular has a lot of leaf carpet spawning on top of the pebbles

**Comment by alcatrazEscapee** [comment]
Sorry, I'm not supporting 1.16.x anymore - if the issue persists in the latest version (1.18.x), please mention or open a new issue.
