### ISSUE TITLE
About porting to mobile

### ISSUE THREAD

**Issue by moxisuki** [alcatrazEscapee/no-tree-punching#216]
Hello, contributors, I am a community developer of the Chinese version of Minecraft, and also a keen player of this mod. I want to port it to the Chinese version of Minecraft for more people to play, because  The code framework is different. The code will be done by myself. There may be a little commercialization, because I may apply it to our sky island server. Thank you, this is just a suggestion :)

**Comment by alcatrazEscapee** [comment]
This has nothing to do with my mod or it's issue tracker then as you can feel free to do whatever you want with this mod provided you obey the [license of the mod](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.16.x/LICENSE.md).

> There may be a little commercialization

And, of course, you should be very familiar with the [Mojang End User License Agreement](https://account.mojang.com/documents/minecraft_eula).

**Comment by moxisuki** [comment]
i will follow，NetEase minecraft is a platform allowed by mojang. thank a lot!
