### ISSUE TITLE
Pebbles are formed in the air

### ISSUE THREAD

**Issue by 1-weibai-1** [alcatrazEscapee/no-tree-punching#217]
Hello, Alex O'Neill
I found a bug when I changed mod
This figure:
![2022-02-19_16 19 54](https://user-images.githubusercontent.com/80395580/154793241-4c96312b-e63a-4dd3-9a68-b2297e3bb464.png)

**Comment by alcatrazEscapee** [comment]
In the words of a very wise modder...

![Lake Feature](https://cdn.discordapp.com/attachments/733824894092968018/860197859059171348/8aljebcsrw321.png)

aka, this is due to the vanilla lake feature, which is a vanilla bug I can't fix because of how awfully they generate.

**Comment by 1-weibai-1** [comment]
Thank you for your answer, Alex O'Neill
