### ISSUE TITLE
[1.12.2] Add grass oreDict if possible

### ISSUE THREAD

**Issue by Pingu-Pox** [alcatrazEscapee/no-tree-punching#218]
Hello! Sorry to bug about an old unsupported version. I just wanted to ask if you could add functionality to this line in HarvestBlockHandler.java so it allowed plant fibers to drop from anything in the <ore:grass> oreDict.

https://github.com/alcatrazEscapee/no-tree-punching/blob/59692ae2fdf9547b6cf02daa674a145fe0563fad/src/main/java/com/alcatrazescapee/notreepunching/util/HarvestBlockHandler.java#L96

If you won't, can you advise me on what I could do if I cloned and added the code myself. Would that violate the license you're using if I distributed that modified version in a modpack? Sorry if this is a stupid question.

**Comment by alcatrazEscapee** [comment]
> an old unsupported version

old unsupported versions are by definition unsupported, and so no, I will not be supporting this old version.

I suggest you read the license (my bold):

> **Permission is hereby granted**, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, **modify**, merge, **publish, distribute**, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, **subject to the following conditions**:
> 
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
