### ISSUE TITLE
Beta Feedback - Grindstone

### ISSUE THREAD

**Issue by Lordician** [alcatrazEscapee/no-tree-punching#22]
- [ ] Right clicking with the grinding wheel in hand on the grindstone should place the grinding wheel in the grind stone. This would make it a bit easier to replace the grinding wheel (without having to open a GUI).
- [ ] Right clicking the grindstone if it does not have a grinding wheel in should open the GUI (unless the above gets implemented, then it should place the grinding wheel if you have one in hand, if not, open GUI).
- [ ] It would make more sense if hoppers underneath the grindstone would only remove the outputs rather than (first) the inputs (then everything else).
- [ ] You probably know this already but there is no recipe for the grinding wheel yet.

Thanks for the configs for stuff like the dust amount and the like, that should really help out customize the mod. 👍

**Comment by alcatrazEscapee** [comment]
1 and 2: yes, that sounds good.
3: that would also be good, I know that all of NTP's blocks currently have weird hopper behavior, will look into this.
4. Thanks for the reminder.
