### ISSUE TITLE
Knife recipes broken?

### ISSUE THREAD

**Issue by Dark-Thoughts** [alcatrazEscapee/no-tree-punching#224]
Am using the fabric version of 1.18.2-5.0.1
Only the flint knife recipe seems to be correct. All the other ones just have a lone stick as a requirement and putting that into the crafting grid will give you an iron knife.
![image](https://user-images.githubusercontent.com/15324196/180060065-cde4c7b9-7550-497e-acb3-c68774c041a5.png)

**Comment by alcatrazEscapee** [comment]
Oh shit

**Comment by Dark-Thoughts** [comment]
Sorry, just noticed, but you want to have a look at the saws and mattocks as well. :)
