### ISSUE TITLE
Incomapatibility with dynamic trees

### ISSUE THREAD

**Issue by NicoTheIdiot** [alcatrazEscapee/no-tree-punching#226]
When the setting "Do instamine blocks mine without tool" is enabled,i can mine the dynamic trees trees without an axe. It should only allow me to mine instamine blocks and the logs are not one of them. 

Minecraft version: 1.18.2
Forge version: 40.1.51
Mod version: 5.0.2

**Comment by NicoTheIdiot** [comment]
thank you,i'm really happy and waiting for curseforge to approve the update!

**Comment by MarijnIsN00B** [comment]
Would a backport to 1.16.5 for this fix be possible? If not, are there other ways to fix this in 1.16.5?
