### ISSUE TITLE
Add Farmers Delight compatibility (wood shovel as spoon)

### ISSUE THREAD

**Issue by Landrozaum** [alcatrazEscapee/no-tree-punching#229]
Farmer's Delight mod and No tree punching mod seem to have been made to work together, as the FD has a more rustic type of stove that replaces the campfire, but it's made with iron bars which doesn't make this stove OP, and NTP with FD makes the game look like a survival game, so the only thing I wanted to ask was to add a compatibility option to keep the wooden shovel crafting as it is used as a spoon in Farmer's Delight and I I can't craft the pot because of this.

**Comment by alcatrazEscapee** [comment]
No. I will not re-add recipes that this mod *explicitly disables* because it would invalidate the point of this mod.

You can feel free to add a recipe for the shovel yourself that fits the balance you desire, or simply change the FD's stove recipe which does not require a wooden shovel.
