### ISSUE TITLE
[Suggestion] Broaden ways to get Plant Fiber

### ISSUE THREAD

**Issue by Thessil** [alcatrazEscapee/no-tree-punching#23]
Only being able to get it from tall grass is a little obtuse. Vines should be able to be turned into plant string directly, and normal grass could use atleast a 20% chance. Tall grass is not as common as you might think, I had to find some bone meal before I could get any.

**Comment by alcatrazEscapee** [comment]
Are you aware it drops from normal and double high tall grass? (Not just the two high grass). Additionally, sugarcane, wheat, saplings, melons, pumpkins, and leaves all can be cut using a knife which gives an additional drop of a few plant fiber.

Vines is an oversight though.

**Comment by Thessil** [comment]
Would be nice to update the wiki with that info. And I recall getting the knife an using it for leaves but not getting any plant fiber for it. Ill try it again.
