### ISSUE TITLE
Server config not generated/not working

### ISSUE THREAD

**Issue by Proxwian** [alcatrazEscapee/no-tree-punching#234]
Can't find server config in both config/ and world/serverconfig folders. 

Minecraft 1.18.2
Forge 40.1.80
notreepunching-forge-1.18.2-5.0.4.jar

**Comment by Proxwian** [comment]
Also if I create notreepunching-server.toml in these folders, it does not work as intended

**Comment by Proxwian** [comment]
Wtf, that's wrong commit, it doesn't seems to fix the problem

**Comment by alcatrazEscapee** [comment]
That was the last of a sequence of commits working on config rework - the notable change in that commit was bumping Epsilon to 0.3, which fixed remaining bugs with the new config system. Please read the [changelog](https://github.com/alcatrazEscapee/no-tree-punching/releases/tag/v5.1.0) for what has changed.

**Comment by Proxwian** [comment]
Now I see, thank you!
