### ISSUE TITLE
Incompatibility with OptiFine H7 with 5.04

### ISSUE THREAD

**Issue by ChrisClickbait** [alcatrazEscapee/no-tree-punching#237]
Hey, I've recently updated your mod on my 1.18.2 modpack and found that Optifine is producing this crash. Fresh instance of 1.18.2 with  v. 5.04 of your mod + OptiFine_1.18.2_HD_U_H7 with Forge 40.1.80

Crash occurs upon creation of a new world. 

Console Log: https://paste.ee/p/76XEa 

Crash Report: 
[crash-2022-09-30_20.16.59-server.txt](https://github.com/alcatrazEscapee/no-tree-punching/files/9689208/crash-2022-09-30_20.16.59-server.txt)

Let me know if you need more information!

**Comment by alcatrazEscapee** [comment]
This is nothing to do with my mod, it's optifine being broken on newer Forge versions.

**Comment by ChrisClickbait** [comment]
> This is nothing to do with my mod, it's optifine being broken on newer Forge versions.

Thanks for the response. Appreciate the hard work you do.
