### ISSUE TITLE
Can't get planks [Fabric version]

### ISSUE THREAD

**Issue by teagan75** [alcatrazEscapee/no-tree-punching#238]
When putting logs into my crafting grid with a flint axe it always gives me sticks even tho JEI says I am suppose to get planks. Its not a conflict as the recipe was added by this mod.

Minecraft version 1.19.2
Fabric version 0.14.10

**Comment by alcatrazEscapee** [comment]
It's not a [shapeless](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.19.x/Common/src/main/resources/data/notreepunching/recipes/sticks_from_logs_with_flint_axe.json) [recipe](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.19.x/Common/src/main/resources/data/notreepunching/recipes/oak_planks_with_flint_axe.json), there are in fact two.

**Comment by teagan75** [comment]
I assume I craft them in my 2x2 grid or I would not be able to move on. It is showing up as a shapeless recipe in JEI and works as such but gives only sticks

![image](https://user-images.githubusercontent.com/12485764/205736742-430d9b0f-0279-4a65-bb9c-9598c26ddcfc.png)

**Comment by teagan75** [comment]
i figured it out but it was confusing
