### ISSUE TITLE
Config option to enable to disabled recipes

### ISSUE THREAD

**Issue by deftesthawk** [alcatrazEscapee/no-tree-punching#239]
Some mods require the campfire and wooden/stone tools for crafting recipes so I'd love a config to re-enable them or instead they could always be craftable but you wouldn't be able to use the tools to mine blocks. You could put red text on them that warns the tools are for crafting purposes only.

**Comment by alcatrazEscapee** [comment]
Make a datapack that re-adds them, or change the recipes of these other things.
