### ISSUE TITLE
[Suggestion] Include furnace recipes for Copper and Tin if furnace recipes are enabled.

### ISSUE THREAD

**Issue by Thessil** [alcatrazEscapee/no-tree-punching#24]
So I really wanted to use mostly just the metals, flint, and wood cutting part of this mod, and discovered I can't actually melt tin without the charcoal forge. I don't have your version of Copper Ore enabled, but Im sure other people would encounter the same problem.

**Comment by Thessil** [comment]
Apologies I misspoke, I meant adding furnace recipes for No Tree Punching versions of metals, so that when removing furnace recipes is disabled in config, it will work normally under vanilla minecraft crafting.

**Comment by alcatrazEscapee** [comment]
Ahh, of course. That is a simple addition, thanks for mentioning it.

**Comment by Thessil** [comment]
Thanks, and it's not that the charcoal forge isn't good, I'm just concerned about mod compatability.
