### ISSUE TITLE
[1.18.2] Tetra Tools Compat

### ISSUE THREAD

**Issue by Proxwian** [alcatrazEscapee/no-tree-punching#240]
Some blocks can’t be broken with any of Tetra tool. For example, piston/sticky piston, glowstone, candles, etc.

If I use vanilla tool of the same type, it would break.

Forge 40.1.8, NTP 5.1.0, Tetra 4.10.1

**Comment by alcatrazEscapee** [comment]
This was never going to work with the custom tool system that was in use in versions < 1.20.x, which has now been removed + replaced with using vanilla's tool system - at the cost of various blocks being in general more harvestable.

**Comment by Proxwian** [comment]
Actually, that’s not true. I solved this problem by adding blocks that’s not harvestable into minecraft tag with tool like minecraft/mineable/axe again. You can make smth like this by default.
