### ISSUE TITLE
Ars Nouveau Compat. 1.16.5

### ISSUE THREAD

**Issue by TheeMrCheeky** [alcatrazEscapee/no-tree-punching#241]
Idk if you will since it is on 1.16.5 but ars nouveau trees and be turned into planks with out axe etc. but 2 planks don't make sticks as intended

**Comment by alcatrazEscapee** [comment]
You can feel free to add the recipes yourself with a datapack. NTP does not do this magically or automatically as recipes are explicit and done via json post 1.14.
