### ISSUE TITLE
Compatability Issues with mods that allow gathering bare handed when items are equipped to an inventory slot

### ISSUE THREAD

**Issue by Rivernoodl** [alcatrazEscapee/no-tree-punching#243]
I want to bring up an issue with no tree punching that I'm hoping can get solved.

In my friend's server we are currently using No Tree Punching, Dragon Survival and Bountiful Baubles, among others.  We are currently having issues with some of the mechanics in these mod packs that NTP has been found to suppress.  After some thought, we realized that something about the way that NTP works overides any and all things that are supposed to contradict it.

**Case One: Bountiful Baubles, and curios slot tools**
![BountifulBaubles_Incompatability](https://user-images.githubusercontent.com/114146574/214566580-8f8219dc-41ec-483b-afe5-2bb7bb0e3608.png)
Diamond-clawed Gauntlets are supposed to allow a player to have its effects applied when digging without a tool.  Ideally it enables mining, chopping and digging using the claw's durability instead.  We have found that while using NTP the claw does nothing unless we use it in our hands, which goes against the intention of the tool.  We're hoping that there may be a way to convince NTP to recognize such effects an an exception to the rule.

**Case Two: Dragon Survival and Applying tool effects to barehanded digging**
![image](https://user-images.githubusercontent.com/114146574/214566628-796b02bb-771e-4dc3-9a91-0afbf0d110d5.png)
In this mod, you can become a dragon.  These dragons have a special equipment slot set that applies tools in your inventory to your claws.  Similar to before, no tree punching forbids digging wood or stone barehanded under any circumstances, but this scenario should be treated like one is using a tool as well.

_Is there any way we can make NTP recognize these scenarios as using a tool instead of digging bare-handed?_

**Note**
*This issue was found playing minecraft 1.16.5 using Forge.  It is unknown on my end if another version has a fix or not.

**Comment by alcatrazEscapee** [comment]
> Is there any way we can make NTP recognize these scenarios as using a tool instead of digging bare-handed?

Generally, no. There's no way to detect this in NTP. NTP requires you to use a tool to harvest blocks. These mods allow you to use no tool to harvest other blocks. Those goals are fundamentally at odds, and one *will* override the other.

As it's 1.16.5, NTP itself won't be updated as it's unsupported.
