### ISSUE TITLE
Mattock can harvest stone bricks (and probably other bricks)

### ISSUE THREAD

**Issue by tehdeh** [alcatrazEscapee/no-tree-punching#244]
Mattocks can harvest stone bricks and some brick variants as well as stairs, walls, and slabs.

Steps to reproduce:
1. Have a mattock
2. Mine stone bricks/slabs/stairs/walls
3. Observe the block dropping

**Comment by alcatrazEscapee** [comment]
Does not appear to be the case in 1.20 versions, which has significant changes w.r.t how tool types on blocks are inferred.
