### ISSUE TITLE
Mangrove recipe conflict [1.19.2]

### ISSUE THREAD

**Issue by DexxKnight1** [alcatrazEscapee/no-tree-punching#245]
Constantly Getting warning because of mangrove logs and planks.
Minecraft has added mangrove in the 1.19, and in the mod recipe the mangrove is still defined as a part of **Oh The Biomes You'll Go** mod.
The recipe should be changed, from _byg:mangrove_plank_ to _minecraft:mangrove_planks_ and the same for the mangrove logs.

**Comment by alcatrazEscapee** [comment]
oh yeah...

**Comment by alcatrazEscapee** [comment]
The compat was removed in 1.20, as maintaining individual other mod compat, between mods x versions x loaders is too much of a hassle. I might look into more automatic solutions...
