### ISSUE TITLE
HT's Tree Chop Uncompatible

### ISSUE THREAD

**Issue by Aedhyx** [alcatrazEscapee/no-tree-punching#247]
When using this mod with HT's Tree Chop mod, whenever i try to chop the tree with flint axe the game crashed so i think tis mod is not compatible with tree chop mod

**Comment by tankyap** [comment]
It works fine for me for some reason

**Comment by alcatrazEscapee** [comment]
Without at the very least, a crash log, and specific versions in question, this is entirely undiagnosable.
