### ISSUE TITLE
compatibility for mods that use campfire in crafting recipes 

### ISSUE THREAD

**Issue by optionalduck** [alcatrazEscapee/no-tree-punching#248]
I am playing with farmers delight and it needs a campfire to craft a stove, perhaps a config option for the old campfire crafting recipe could be added for people playing with mods that need it 

edit: also knives in farmers delight are uncreatable also since they share the same recipe but function as no tree punching knives also while the reverse isnt true for no tree punching knives

**Comment by alcatrazEscapee** [comment]
Crafting recipes are always editable via a datapack. If you wish to change either ones - making things craftable which NTP disables, or changing recipes that use these items, you are free to.
