### ISSUE TITLE
There is no recipe for wood when using any type of axe

### ISSUE THREAD

**Issue by moayad155** [alcatrazEscapee/no-tree-punching#250]
There is no recipe for wood when using any type of axe

![لقطة الشاشة 2023-05-05 094514](https://user-images.githubusercontent.com/81738896/236397579-289c51f0-8704-47aa-ab75-c8d975f7aa54.png)
![لقطة الشاشة 2023-05-05 094452](https://user-images.githubusercontent.com/81738896/236397602-591fe2da-27d3-4857-acb6-e4f6abde934e.png)
![لقطة الشاشة 2023-05-05 094427](https://user-images.githubusercontent.com/81738896/236397623-ad0a84db-9ba3-4e59-82aa-1e8b8cc0a1cf.png)

**Comment by alcatrazEscapee** [comment]
This is really a mod compat problem, there's not much I can do here. You are free to edit the other axes to tag them as axes usable in NTPs recipes.
