### ISSUE TITLE
[1.18.2] doBlocksDropWithoutCorrectTool = true allows mining drops with bare hands.

### ISSUE THREAD

**Issue by jaypaw549** [alcatrazEscapee/no-tree-punching#252]
I'm not 100% sure if this is a bug or intended, but right now the following settings allows you to mine any block with your bare hands and get the block drop.

```
    # If blocks are mineable without the correct tool.
    doBlocksMineWithoutCorrectTool = true

    # If blocks drop their items without the correct tool.
    doBlocksDropWithoutCorrectTool = true
```

I've already pinpointed the potential issue as being [here](<https://github.com/alcatrazEscapee/no-tree-punching/blob/8b061267712aa3016d45246bcca606b0f28b0b15/Common/src/main/java/com/alcatrazescapee/notreepunching/EventHandler.java#L36>), where the result is OR'd (`||`) with the harvest check code instead of AND'd (`&&`).

**Comment by alcatrazEscapee** [comment]
Yeah, that config option does what it says on the tin. The `||` behavior is intentional too, as it's intending to widen vanilla's harvest check - if vanilla's harvest check passes, it needs to harvest because NTP's behavior will almost always fail. Or at least, that's the theory.
