### ISSUE TITLE
Unable to Craft Oak Planks: Hindering Game Progression

### ISSUE THREAD

**Issue by ocarinayoy** [alcatrazEscapee/no-tree-punching#253]
I've been trying out your mod and I really appreciate all the effort and mechanics you've put into it. However, I have a couple of issues. I'm playing Minecraft Fabric v1.20, and here's the problem: I started my playthrough by searching for flint and other materials to craft the flint axe. Once I finally obtained it, I attempted to craft wood planks by placing my flint axe and a stripped log in the recipe GUI. The thing is, right at the beginning of the game, I don't have any wood planks or minerals to craft a saw. So I decided to check out the REI mod (Roughly Enough Items) to figure out how to craft wood planks. Surprisingly, there are only two options available: using a stripped log with a flint axe or using a saw with regular logs. However, when I choose the only alternative I currently have to obtain wood planks, it doesn't work as expected. Instead of receiving wood, I only end up with sticks as a result of the crafting recipe. I'm not sure if this is intentional or if there's something I'm missing in terms of how to use the mod effectively. It's quite confusing to me, and I'm struggling to understand how to properly play with this mod.

A few days ago, I tried out the beta release of the mod on modrinth.com, and I encountered that issue. And also another one with the stone and wooden recipes for tools were still present. However, now that I'm playing the release version, the problem with the tools seems to have been resolved. Unfortunately, though, I'm still facing the ongoing issue of not being able to obtain wooden planks. It's puzzling why this problem persists despite the updates.

Note: Just as a suggestion, I've been combining this mod with the Dehydration mod currently available on modrinth.com. One of the main mechanics introduced by Dehydration is the use of campfires to heat and purify water. However, your mod doesn't allow crafting campfires anymore. So, what if we reintroduce campfires, but instead of rendering the Fire Starter tool useless, we could implement a feature where the campfires are initially unlit when placed, and then your tool could be used to ignite them again, thus making these two mechanics compatible with each other.

I would greatly appreciate it if you consider this suggestion. Love your work <3

**Comment by alcatrazEscapee** [comment]
https://github.com/alcatrazEscapee/no-tree-punching/assets/35673674/f162d94b-1875-4803-9b8b-fa131a6e9fe9
