### ISSUE TITLE
Suggestion: option for disable mining some soft blocks

### ISSUE THREAD

**Issue by DcNdrew** [alcatrazEscapee/no-tree-punching#258]
Hi!
I have other ways to find flint than mining gravel. Not to mention that you can buy tools from villagers too.
Can you make an option for disable mining gravel, dirt, grass and sands? It would be nice if the players won't be able to mess around while they don't have the proper tools.

**Comment by alcatrazEscapee** [comment]
You are already able to do this via a datapack which replaces a block tag. It is documented [here](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking#configuration)
