### ISSUE TITLE
Boat recipe in 1.20 needs a wooden shovel

### ISSUE THREAD

**Issue by Tar1q22** [alcatrazEscapee/no-tree-punching#259]
Like the title says, in 1.20 the recipe for boats in Java edition was changed to require a wooden shovel, like in bedrock. This is a problem because it means that boats are unobtainable with this mod since you can't craft a wooden shovel anymore. This could either be fixed by allowing only the wooden shovel (and maybe hoe for good measure) to be crafted, or by adding a new oar item to be used in the recipe for boats.

**Comment by alcatrazEscapee** [comment]
This is made up?

https://minecraft.wiki/w/Java_Edition_15w41a

> Crafting recipe now includes a [wooden shovel](https://minecraft.wiki/w/Wooden_shovel) for the oars.

https://minecraft.wiki/w/Java_Edition_15w41a

> Crafting recipe no longer requires wooden shovel.

https://minecraft.wiki/w/Boat

The boat recipe does not require a wooden shovel.
![image](https://github.com/user-attachments/assets/5667edcd-292a-4d3b-b47b-3901976f83be)
