### ISSUE TITLE
Block don't drops when tool breaks down

### ISSUE THREAD

**Issue by QuantumStatement** [alcatrazEscapee/no-tree-punching#26]
Minecraft 1.12.2
Forge 14.23.3.2655
No Tree Punching 1.3.4-beta4

When tool (axe, saw, pickaxe etc.) breaks down, block mined with this tool don't drops. This bug affects vanilla and NTP tools (maybe tools from other mods too).

**Comment by alcatrazEscapee** [comment]
So the issue here is that the item takes damage before the block drops are calculated, which is when NTP executes its block breaking logic. I am looking into ways around this but so far I don't know how to get around it.

**Comment by alcatrazEscapee** [comment]
See https://github.com/MinecraftForge/MinecraftForge/issues/4384#issue-256413765
