### ISSUE TITLE
Flowers obtainable without hoe

### ISSUE THREAD

**Issue by xeaal** [alcatrazEscapee/no-tree-punching#262]
Hello. Can you please make it so that flowers are obtainable without a hoe? I am playing with a mod that requires flowers to make healing items and just couldn't get any before I could get a hoe. I can understand needing a knife or shears (better both of them, being interchangeable) but not hoe! You can just make it so you can use all of these three items, knife, shears and a hoe to get flowers.

**Comment by leftbones** [comment]
I second this suggestion, I can pick flowers in real life without any tools if I harness the raw muscular power required to do so

**Comment by Arcirion** [comment]
Even with a hoe small flowers don't drop anything? How do you get it to work?

**Comment by alcatrazEscapee** [comment]
Duplicate of #309
