### ISSUE TITLE
Cannot Craft Planks

### ISSUE THREAD

**Issue by cooper59** [alcatrazEscapee/no-tree-punching#263]
When I try to craft planks using an axe it makes 6 sticks. 1.20.1 version

**Comment by cooper59** [comment]
nvm

**Comment by Komi-ram** [comment]
Apologize for asking, but how did you solve this? I'm currently stuck unable to figure out how to make planks. Thanks!

**Comment by cooper59** [comment]
This is weird. So I looked at the other comments and somehow I put in the crafting table a certain way and it worked. Now it doesn't again..

**Comment by cooper59** [comment]
I put the axe back above the logs but now it only works with one mod's wood

**Comment by cooper59** [comment]
*It works with some logs but not others. Like I can't craft planks out of oak jungle or cherry logs

**Comment by alcatrazEscapee** [comment]
Duplicate of #310
