### ISSUE TITLE
Inconsistency with ability to break blocks

### ISSUE THREAD

**Issue by ghost** [alcatrazEscapee/no-tree-punching#266]
When creating new modpacks sometimes I am prevented from breaking blocks completely (which I prefer) and sometimes I'm able to break blocks without drops instead. 
Also used a mod with modded trees before (promenade) and was able to punch down modded trees  with drops.

Using CurseForge Fabric MC 1.20.1

**Comment by alcatrazEscapee** [comment]
This is likely Promenade's fault, as they don't tag their wood blocks as [mineable with an axe](https://github.com/DawnTeamMC/Promenade/blob/main/src/main/resources/data/minecraft/tags/blocks/mineable/axe.json)

**Comment by ghost** [comment]
Ah I see, I removed the mod anyway, thanks for the explanation. I guess I worded the other issue wrong though, I checked out the config file and it seems the doBlocksMineWithoutCorrectTool = false does not work with any blocks and I'm still able to break them punching (though without drops which is good). When creating a different modpack it prevented me from breaking blocks just fine and I'm not sure what's causing the problem. Any idea if something could be interfering with it and how? Just wondering if there's anything I can do to make the feature work correctly, but I can't figure out what kind of mod could cause it
