### ISSUE TITLE
Oak plank recipe is not working with weak_saw tag

### ISSUE THREAD

**Issue by YejiYeah** [alcatrazEscapee/no-tree-punching#268]

**Comment by YejiYeah** [comment]
Fabric: 0.14.22
Mod version: 1.20-7.1.0
![image](https://github.com/alcatrazEscapee/no-tree-punching/assets/77309538/15ea0801-fc23-4e3b-9b2b-6af68ae84544)

**Comment by YejiYeah** [comment]
Mc version 1.20.1

**Comment by alcatrazEscapee** [comment]
Duplicate of #310
