### ISSUE TITLE
Option to disable certain blocks from being mined with flint pickaxe. 

### ISSUE THREAD

**Issue by spicyhoodman** [alcatrazEscapee/no-tree-punching#270]
I was wondering if it would be possible to add an option/config to disable the flint pickaxe from being able to mine certain blocks, such as iron ore. For context, the idea for progression in my mod pack would be, flint pickaxe can mine copper ore -> copper pickaxe can mine iron ore -> iron obtained. 
[Fabric 1.20.1]

**Comment by alcatrazEscapee** [comment]
This is doable with the existing vanilla tags for mine-ability i.e. `needs_diamond_tool` and the corresponding NTP tag `notreepunching:needs_flint_tool`
