### ISSUE TITLE
Add stick recipes to enableDynamicRecipeReplacement

### ISSUE THREAD

**Issue by DuffieShirayuki** [alcatrazEscapee/no-tree-punching#271]
Please add stick recipes to enableDynamicRecipeReplacement in the config, so you don't have to use an axe or saw to craft sticks when it is set to false

**Comment by alcatrazEscapee** [comment]
Stick recipes aren't dynamic, and can be disabled or edited via datapacks, unlike log -> plank recipes, so no.
