### ISSUE TITLE
[Suggestion] More ways to get sticks

### ISSUE THREAD

**Issue by leftbones** [alcatrazEscapee/no-tree-punching#275]
If this goes against the philosophy of this mod, then feel free to say so and close this issue.

I've been making a modpack that includes this mod and I've done a few playtests now, and each time I'm realizing that early game success depends heavily on where you spawn. Basically it comes down to if there are trees nearby and if there is surface gravel nearby.

However, if you spawn in a desert, mesa, or some biome that doesn't have any trees or nearby leaves or anything, you're kind of screwed. I spawned in a mesa once that had just dead bushes. According to the Minecraft wiki, dead bushes are supposed to drop 0-2 sticks when broken without a tool. I broke every single dead bush I could find and didn't get a single stick. Not sure if this mod specifically changed that, but it was frustrating to say the least.

So, for starters, adding a chance to drop sticks from dead bushes would be a great idea, I think. They tend to only spawn in areas with no trees anyways, so I don't think it would do any harm.

Another idea I had was to have loose sticks on the ground, like the loose stones. There's another mod that does something like this called [Twigs](https://www.curseforge.com/minecraft/mc-mods/twigs), which is awesome, except it's not compatible with this mod. You're able to break all of the seashells, rocks, and twigs with your hands, but they won't drop anything.

So loose sticks would help with this. Not nearly as common as loose rocks, of course, perhaps only spawning on grass blocks and at a much lower rate, or maybe only near the base of trees? Punching leaves is just annoying, lol. Even adding twigs would be cool, maybe sticks could be crafted with 4 twigs or something, like how the loose stones can be combined into various stone blocks.

**Comment by thequietestgirl** [comment]
Created a github account just to agree with you on this. I'm also making a modpack and I think scattered sticks is a really good idea.

**Comment by alcatrazEscapee** [comment]
I am not particularly interested in expanding the mod via scattered sticks on the ground. For the dead bush issue and other mod compat, see #309
