### ISSUE TITLE
Can't create campfire in "No Tree Punching" mod

### ISSUE THREAD

**Issue by SandwichDream** [alcatrazEscapee/no-tree-punching#279]
Can't create campfire in "No Tree Punching" mod

**Comment by SandwichDream** [comment]
I found the recipe. Everything is normal

**Comment by tygoee** [comment]
@SandwichDream how did you make one?

**Comment by SandwichDream** [comment]
> @SandwichDream how did you make one?

As I remember, 2 two blocks of wood and three sticks
