### ISSUE TITLE
Game crashes when loading.

### ISSUE THREAD

**Issue by Priderino** [alcatrazEscapee/no-tree-punching#28]
Game crashes when I load it.
NTP: 1.4.0
Forge: 14.23.4.2705 and also  14.23.4.2707
https://paste.ee/p/7JGrZ

**Comment by alcatrazEscapee** [comment]
I can't reproduce this. Can you try with just NTP and forge? Also use the recommended 2705 version of forge?

**Comment by Priderino** [comment]
This is the crash report with forge 2705 and without the other mods:
https://paste.ee/p/DH6hf

**Comment by alcatrazEscapee** [comment]
I can't get this to crash... This is so strange.

**Comment by alcatrazEscapee** [comment]
Ok, I got it to crash, but then replaced it with a new build (with nothing changed,) and it didn't crash. Can we just assume that fixed it somehow??

**Comment by Priderino** [comment]
That's the weirdest crash ever, but if the new build solves the problem, I'm all in.

**Comment by alcatrazEscapee** [comment]
Ok, released a new build 1.4.1b. Once Curseforge is done processing, try that and let me know if it keeps happening.

**Comment by Priderino** [comment]
Yeah, no more crashes, but holy, that's a lot of stones. (Using 1.4.1c)

**Comment by alcatrazEscapee** [comment]
There is a config setting for that. The default was a bit too high 👍
