### ISSUE TITLE
No Tree Punching causes a bug with Ore Stone Variants

### ISSUE THREAD

**Issue by TheEffortFighter** [alcatrazEscapee/no-tree-punching#284]
Game Version: 1.18.2

Forge Version: 40.2.14

Mod versions:
NoTreePunching: notreepunching-forge-1.18.2-5.1.0.jar
Ore Stone Variants: OSV-Forge-7.11-BETA.jar

Problem:
If you remove No Tree Punching from the mod pack, Ore Stone Variants stop working, and ores no longer drop.

**Comment by alcatrazEscapee** [comment]
I am not supporting 1.18 anymore; neither does NTP make any modifications that persist beyond the mod being present.
