### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by Thaison2014** [alcatrazEscapee/no-tree-punching#285]
for some reason when i break leaves i get sapling instead of sticks

**Comment by Thaison2014** [comment]
anyone?

**Comment by definitelynotklip** [comment]
> for some reason when i break leaves i get sapling instead of sticks

Getting sticks from leaves is actually pretty rare. You'll get one if you keep trying (don't use shears) but I'd actually recommend installing either the mod [This Rocks!](https://www.curseforge.com/minecraft/mc-mods/this-rocks) for Fabric or [Project: Vibrant Journeys](https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys) for Forge that place random bits and bobs on the ground, such as rocks, twigs, and shells, and collecting sticks from the ground that way.

Alternatively, you could make a custom recipe to convert saplings into sticks using [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker). You'd have to create a new file with a `.zs` extension named whatever you want. It would be placed inside the new `scripts` folder created in the root directory of the game after it is ran with the mod at least once. Then you'd paste the following syntax into it:

```
craftingTable.addShapeless("sapling_to_sticks", <item:minecraft:stick> * 2, [<tag:items:minecraft:saplings>]);
```
This would allow you to convert any sapling into two sticks using any type of crafting grid. You can change the amount of sticks you'd get from the recipe by modifying the `* 2` part.
