### ISSUE TITLE
Compatibility with Better Combat?

### ISSUE THREAD

**Issue by PPMDJ** [alcatrazEscapee/no-tree-punching#288]
Would be nice for the macuahuitl to have built-in compatibility with Better Combat. I was able to get the macuahuitl to have sword stats by adding in the macuahuitl in their "fallback_compatibility.json" file:

"item_id_regex": "sword|blade|macuahuitl",
"weapon_attributes": "bettercombat:sword"

The knife and axe also works correctly with their fallback compatibility identifying NTP's flint knife as a knife. BUT regardless it might be nice to make this default in NTP (or, at least but instructions in the description of the mod webpage so that people can do this step themselves). Better Combat has descriptions on how to do this in the code at https://github.com/ZsoltMolnarrr/BetterCombat#-integrate-your-mod. This would be done with the knife, macuahuitl, and mattocks.

**Comment by alcatrazEscapee** [comment]
I am not interested in adding compatibility myself with better combat at present
