### ISSUE TITLE
Charcoal Forge generating Granite

### ISSUE THREAD

**Issue by Priderino** [alcatrazEscapee/no-tree-punching#29]
I don't know if this is intended, but if you leave the charcoal forge without any inputs, it starts to consume the coal and generates Granite.
http://prntscr.com/jq002g

**Comment by alcatrazEscapee** [comment]
Can you check the config option for `STONE_DROPS_ROCKS`?

**Comment by Priderino** [comment]
I changed it to false.

**Comment by alcatrazEscapee** [comment]
Ah ok. Those recipes shouldn't of loaded, as they are trying to smelt granite cobblestone, which doesn't exist.

**Comment by Priderino** [comment]
Also, i'm trying to raise the temperature of the forge to try and get Bronze, but even with the bellows+tuyere and spamming right click on a lever, the temperature stays the same.

**Comment by Priderino** [comment]
I'm really interested in using this as a core more for the early game on my pack, so I might be bothering you a lot with suggestions and bug reports, if needed.

**Comment by alcatrazEscapee** [comment]
Can you post a picture of your setup? I have the forge running fine in my dev environment. Also, bother away! I like hearing what people think. 👍

**Comment by Priderino** [comment]
About my setup, the bellow were wrongly placed, it's working now.

**Comment by alcatrazEscapee** [comment]
Ahh perfect
