### ISSUE TITLE
plant break no drop BUG

### ISSUE THREAD

**Issue by StistkoHraje** [alcatrazEscapee/no-tree-punching#290]
So I wanted to use this mod in my modpack but thare is an issue if you break any plant or flower it doesent drop anything, doesent matter what tool I use it doesent drop anything, can it be made to harvest plants and flowers with hand and any tool? I like the wood mechanic of not droping wood when destroyed by hand and I love the pottery, but the flowers and plants not droping when Destroyed is a big problem.

**Comment by StistkoHraje** [comment]
I am playing on version 1.20.1

mod version: Fabric-1.20-7.1.0

issue: vanila plants and mod plants dont drop items when broken

**Comment by StistkoHraje** [comment]
+question will you make a mod that only adds the pottery from your mod?

**Comment by elpideus** [comment]
I am trying to see what's wrong. It is probably the load order of the mod. I am now doing some tests. I will keep you updated.

**Comment by alcatrazEscapee** [comment]
Duplicate of #309
