### ISSUE TITLE
Game Crashes when Creating a New World

### ISSUE THREAD

**Issue by Squigsmasha** [alcatrazEscapee/no-tree-punching#291]
Hello,
I encountered an interesting issue with this mod after I assembled a custom modpack. When I go to create a world, halfway through the loading time to get to the world options, the game crashes. I checked the logs and they stated No Tree Punching was throwing a null pointer exception. I provided the logs and crash report so you guys can look at it, too. I disabled the mod and started the game without it, and I was able to proceed to the world options. I don't know if there is a mod incompatibility or something, but it might be a good idea to look into. 

[2024-03-09-4.log](https://github.com/alcatrazEscapee/no-tree-punching/files/14548312/2024-03-09-4.log)
[2024-03-09-4.log.gz](https://github.com/alcatrazEscapee/no-tree-punching/files/14548315/2024-03-09-4.log.gz)
[crash-2024-03-09_17.25.58-client.txt](https://github.com/alcatrazEscapee/no-tree-punching/files/14548314/crash-2024-03-09_17.25.58-client.txt)

**Comment by alcatrazEscapee** [comment]
I am not supporting 1.19.2 anymore.
