### ISSUE TITLE
No tool harvests small flowers

### ISSUE THREAD

**Issue by Arcirion** [alcatrazEscapee/no-tree-punching#292]
Previous posts mention a hoe can harvest small flowers but this no longer seems to be the case. I can't find a single way in survival mode to harvest small flowers.

**Comment by Midnight-GHub** [comment]
Facing the same issue in fabric-1.20-7.1.0

**Comment by vainangel** [comment]
Same issue on Forge-1.20.1-7.1.0

**Comment by ginsm** [comment]
There's a config file (`notreepunching.toml`), at least for Fabric 1.20.1-7.1.0, that allows you to change this behavior. Set `doInstantBreakBlocksDropWithoutCorrectTool` to `true` and the flowers will drop their items again.

EDIT: This also works for modded plants (#272). This likely works as a workaround for #273, #264, and #290 as well.

**Comment by alcatrazEscapee** [comment]
Duplicate of #309
