### ISSUE TITLE
cannot craft tools[1.19.2]

### ISSUE THREAD

**Issue by TheRealDoomSlayer69** [alcatrazEscapee/no-tree-punching#295]
Wooden and stone tools are uncraftable

**Comment by TheRealDoomSlayer69** [comment]
or is it intended? At least make only stone tools craftable to get iron

**Comment by alcatrazEscapee** [comment]
It's listed as a feature in the mod description so yes, it is intentional...

> Vanilla recipes for wooden and stone tools have been removed.
