### ISSUE TITLE
I need compatibility with the "Dehydration" mode

### ISSUE THREAD

**Issue by Pandorum301** [alcatrazEscapee/no-tree-punching#304]
The "No Tree Punching" mod removes the bonfire crafting recipe that is needed for the "Dehydration" mod. It would be great if you added compatibility to them. You can do this: return the crafting of the bonfire, but in order for the bonfire to burn, you need to put fuel (coal) in it and light it with Fire Starter.

**Comment by alcatrazEscapee** [comment]
You can add or edit crafting recipes with a [datapack](https://minecraft.wiki/w/Data_pack) if needed.
