### ISSUE TITLE
request: whitelist 

### ISSUE THREAD

**Issue by TheSexyYeti** [alcatrazEscapee/no-tree-punching#305]
Can you add a whitelist to the configs, for the fabric version, that let's you whitelist breakable items. I was working on this mod pack. and for some reason I was getting no sticks at all from breaking leaves. So to fix this issue I added the terraqueous mod for the sticks and stones that it spawns in the world naturally. But because your mod prevents breaking objects without the proper tool. It wouldn't even let me break any of the sticks or stones. So I was forced to just take both of the mods out.

**Comment by alcatrazEscapee** [comment]
You can configure the [block tag](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking#configuration) that do not require a tool with a datapack.
