### ISSUE TITLE
Despite having configs...

### ISSUE THREAD

**Issue by ThatLittleCrab** [alcatrazEscapee/no-tree-punching#306]
You still can't break blocks that you should be able to with your bare hands

i.e Path blocks (You can break dirt so...), sand, clay, literally anything that can be quickly excavated by a shovel is impossible to break no matter what config, which makes no sense for the mod itself that allows you to break dirt and gravel anyway.

**Comment by alcatrazEscapee** [comment]
You can configure the [block tag](https://github.com/alcatrazEscapee/no-tree-punching/wiki/BlockBreaking#configuration) that do not require a tool with a datapack.
