### ISSUE TITLE
No more new Gold Tools?

### ISSUE THREAD

**Issue by Thessil** [alcatrazEscapee/no-tree-punching#31]
I know gold isn't exactly the ideal tool material but it has a purpose in Minecraft, to be the most enchantable. So why no more gold mattock, knife and saw? Are enchantments not effective on those kinds of tools yet?

**Comment by alcatrazEscapee** [comment]
Ok, I'll put them back.

**Comment by alcatrazEscapee** [comment]
Fixed in 1.4.2
