### ISSUE TITLE
Knives incompatible with Farmer's Delight

### ISSUE THREAD

**Issue by PlayerXYT** [alcatrazEscapee/no-tree-punching#312]
Knives have the same recipe as the ones provided by Farmer's delight. This makes one mod unusable, in this case NoTreePunching takes precedence and overrides the other recipe in the crafting table.

See [#96](https://github.com/MehVahdJukaar/FarmersDelightRefabricated/issues/96)

**Comment by alcatrazEscapee** [comment]
This seems to be entirely solvable by the pack maker, either by changing recipes (datapack), or choosing one or the other as both functionality, that I can see, relies on tags. Although NTP knives are likely less out-of-the-box compatible due to #300
