### ISSUE TITLE
Create incompatiblity

### ISSUE THREAD

**Issue by Mlig317** [alcatrazEscapee/no-tree-punching#315]
I'm not sure why but fabric 1.20.1, no tree punching + create results in being unable to cut grass with a knife. Like the block breaks but you never get plant fibers

**Comment by Mlig317** [comment]
sorry, thats incompatibility with farmers delight, not create

**Comment by alcatrazEscapee** [comment]
Duplicate of #309

**Comment by Mlig317** [comment]
This is to say what exactly? that I need to create my own datapack if i want notreepunching to work with farmers delight?
