### ISSUE TITLE
Broken Knives Texture/Models

### ISSUE THREAD

**Issue by YisusClaus** [alcatrazEscapee/no-tree-punching#318]
**Are the Knives textures/models supposed to be broken?**

![Knives](https://github.com/user-attachments/assets/23c7bdeb-9cd9-40d3-938d-a4b19b0de902)

**Tested on:**
- **_notreepunching-forge-1.20-7.1.0_**
- **_notreepunching-fabric-1.20-7.1.0_**

**Comment by alcatrazEscapee** [comment]
Duplicate of #299
