### ISSUE TITLE
Iron ore can't be smelted

### ISSUE THREAD

**Issue by Stormwind99** [alcatrazEscapee/no-tree-punching#34]
It seems I can no longer smelt iron ore - it no longer works in the charcoal forge, and the blast furnace turns it directly into steel ingots.  Both were fully stocked with charcoal but no bellows (I haven't found any tin to make bronze with yet).

(Sorry if a rule change I missed causes this behavior.) 

Thanks for the fun mod!

**Comment by alcatrazEscapee** [comment]
If you look at the charcoal forge iron recipe, you can see the temperature gauge on the left hand side requires a temperature of 1500 (max temperature). On its own, the forge only reaches 1000 (roughly 2/3) Smelting iron is only possible with bellows, and very consistently pumped bellows at that. See [Bellows and Tuyere](https://github.com/alcatrazEscapee/no-tree-punching/wiki/Tuyere) for how to use.

Blast Furnace turning iron into steel is intended. That way it follows the progression line:
Copper + Tin -> Bronze -> (crafts) Bellows (which allows you to smelt) -> Iron (crafts blast furnace, which gives) -> Steel.
