### ISSUE TITLE
No bronze dust recipe

### ISSUE THREAD

**Issue by WazWaz** [alcatrazEscapee/no-tree-punching#35]
Possibly I'm looking in the wrong place, but I couldn't find any form of dust_copper+dust_tin recipe for making dust_bronze. Tested with NTP 1.4.3 alone, no other mods.

**Comment by alcatrazEscapee** [comment]
Whoops. That must of gotten missed when I moved all the metalworking recipes. Will fix soon.

**Comment by alcatrazEscapee** [comment]
Fixed in 1.4.4
