### ISSUE TITLE
JEI info only goes "forward"

### ISSUE THREAD

**Issue by WazWaz** [alcatrazEscapee/no-tree-punching#36]
eg. if you look up charcoal, you'll be told how to use it, but to find out how to get it, you need to look up logs. Ideally, both would exist.

Related, is there supposed to be a log->charcoal furnace recipe? It makes the charcoal pit pointless (9 logs makes 8 charcoal in furnace, but only 4-5 in charcoal pit).

**Comment by alcatrazEscapee** [comment]
Fixed in 1.4.5
