### ISSUE TITLE
Tinkers' Construct mattocks are made ineffective

### ISSUE THREAD

**Issue by notjoe7F** [alcatrazEscapee/no-tree-punching#38]
When trying to break blocks like dirt and logs using a Tinkers' mattock, the block breaks slower than it should and does not drop anything (as if the incorrect tool was being used).

Other "multi-tools" such as the Actually Additions AIOT seem to work fine. Other Tinkers' tools (pickaxes, shovels, hammers...) also appear to work properly.

Tested with Minecraft 1.12.2, Forge 14.23.4.2705, Tinkers' Construct 2.10.1.87 and No Tree Punching 1.4.5.

**Comment by alcatrazEscapee** [comment]
This should be fixed in 1.4.6
