### ISSUE TITLE
Loose Rocks generates in water

### ISSUE THREAD

**Issue by QuantumStatement** [alcatrazEscapee/no-tree-punching#39]
Minecraft 1.12.2
Forge 14.23.4.2705
No Tree Punching 1.4.6

In new version of mod Loose Rocks generates in water
1.4.6
![2018-07-15_21 49 23](https://user-images.githubusercontent.com/35406698/42737260-c8adf3c2-8879-11e8-80c2-5d811a9aefb0.png)

1.4.5, same world
![2018-07-15_21 37 34](https://user-images.githubusercontent.com/35406698/42737258-c6a5a5de-8879-11e8-838b-cf262af97ced.png)

**Comment by alcatrazEscapee** [comment]
Thanks, should be fixed in 1.4.7
