### ISSUE TITLE
[Suggestion] Milk Ceramic Bucket

### ISSUE THREAD

**Issue by QuantumStatement** [alcatrazEscapee/no-tree-punching#40]
Since No Tree Punching have ceramic buckets, I think it would be good to allow use them with milk (get milk from cows, craft a cake, drink milk to wear out potion effects)

**Comment by alcatrazEscapee** [comment]
Did you try:
1. In the config, adding "milk" to the list "CLAY_BUCKET_FLUIDS" and
2. Adding a mod that makes milk a fluid (it is not a fluid in vanilla IIRC, something like Thermal series should do it)
It should already be a feature.

**Comment by QuantumStatement** [comment]
1. Yes
2. Yes (I'm used Forestry for that)

**Comment by alcatrazEscapee** [comment]
Hmm, that should be working then. I'll have a look when I get home.

**Comment by alcatrazEscapee** [comment]
Are you asking if milk buckets exist? Or if they obey the above behavior?

**Comment by alcatrazEscapee** [comment]
I'm not planning to add another fluid just for this case. I might look into other behavior at some point, presuming another mod adds the respective fluids.
