### ISSUE TITLE
how do i smelt iron?

### ISSUE THREAD

**Issue by krisztian08** [alcatrazEscapee/no-tree-punching#44]
i tried in both furnace and charcoal forge,i dont know how :(

**Comment by alcatrazEscapee** [comment]
By default NTP will disable ingot smelting in the furnace.
The charcoal forge is able to smelt iron, however it requires a higher temperature than it can reach alone. You need a [Tuyere](https://github.com/alcatrazEscapee/no-tree-punching/wiki/Tuyere) and bellows to get the temperature up to maximum.
