### ISSUE TITLE
Minecraft won't launch

### ISSUE THREAD

**Issue by ScienceDrummer** [alcatrazEscapee/no-tree-punching#48]
I'm only going off of what the crash report is telling me. Please correct me if I'm wrong. https://pastebin.com/8ci4JGs3

**Comment by underr** [comment]
I also can reproduce this error.

Log: https://ghostbin.com/paste/gx7ob

**Comment by alcatrazEscapee** [comment]
What in the heck...
I rebuilt the project and it stopped crashing for me, we'll see if that worked.
