### ISSUE TITLE
[Suggestion] Any axe to recipe planks from wood

### ISSUE THREAD

**Issue by wenlfs** [alcatrazEscapee/no-tree-punching#49]
The recipe now use only the Crude axe to get planks, accept any axe tool would be good when you already have access to high tier materials.

Also, both of recipes to get planks (using saw or crude axe) are duplicated

Thank you for you amazing work

**Comment by alcatrazEscapee** [comment]
That is what saws are for: precision chopping of wood. Duplicate recipes are probably due to some ore dictionary weirdness. They only seem to be duplicated on vanilla recipes anyway.

**Comment by wenlfs** [comment]
My idea was that using an axe tool you get less planks than using a saw, as it already are since you get 2 using the Crude axe.

Thank you anyway.
