### ISSUE TITLE
server crash on 2.0.0

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#50]
(reposting here as requested)

So bit of a strange bug here.  The latest version 2.0.0 I can play just fine in single player.  I can even host a LAN game and have a friend join.  However, I cannot host a server directly, using the same version of forge and everything.  Server will crash.  The previous version before this 1.4.13 crashes both client and server, tested with forge forge-1.12.2-14.23.4.2755 and forge-1.12.2-14.23.4.2760.

The crash log (for the 2.0.0 crash) spams something about:

at net.minecraftforge.fluids.UniversalBucket.func_77653_i(UniversalBucket.java:134) at net.minecraftforge.fluids.UniversalBucket.func_77653_i(UniversalBucket.java:134) at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)

Full crashlog here:  
[crash-2018-10-10_16.14.34-server.txt](https://github.com/alcatrazEscapee/no-tree-punching/files/2466840/crash-2018-10-10_16.14.34-server.txt)

**Comment by alcatrazEscapee** [comment]
Should be fixed in 2.0.1
