### ISSUE TITLE
Mod overrides crafttweaker changes.

### ISSUE THREAD

**Issue by Waynekosimoto** [alcatrazEscapee/no-tree-punching#53]
I disabled stone tools in crafttweaker in order to add a modified recipe using items from another mod, but this mod overrides crafttweaker and removes my custom crafttweaker recipes. Changing the config file to enable stone tools, force enables the stone tool recipes that I had disabled via crafttweaker while at the same time restoring my custom recipes.

**Comment by alcatrazEscapee** [comment]
I can't seem to reproduce this. I setup a test world and was able to add a crafttweaker recipe for the stone pickaxe, and remove the original one with NTP 2.0.5.

1. What versions of NTP / Forge / Craft Tweaker were you running?
2. I'm assuming you mean you set `replaceVanillaRecipes = false` when you said you enabled stone tools via NTP's config?
3. Did you check that the recipe was just not showing up in JEI?

**Comment by Waynekosimoto** [comment]
Well, I figured it out. One of my scripts had a typo. The weird part is that it has nothing to do with stone tools and it should have had no effect on those recipes. Well anyways before you close this issue, could you answer this question? What is the ID of the firepit and will it be possible to remove or add recipes to it with crafttweaker? Sorry and thanks

**Comment by alcatrazEscapee** [comment]
No worries. In answer to your question, yes it is possible, syntax can be found here: https://github.com/alcatrazEscapee/no-tree-punching/wiki/Craft-Tweaker-Integration
