### ISSUE TITLE
[Suggestion] Ability to change firepit creation requirements.

### ISSUE THREAD

**Issue by Waynekosimoto** [alcatrazEscapee/no-tree-punching#54]
In order to make a firepit you need one wood, three sticks and one piece of string. I would like the ability to add more types of string. I'm trying to make 4 different "survival/primal" mods work together so it's important to keep the grass/thatch/straw/plant fibers unified.

**Comment by alcatrazEscapee** [comment]
1. What version of NTP are you using? And
2. In 2.0.0+ the fire pit creation is from the following ore dictionary inputs: 1x `logWood`, 3x `stickWood`s, and 1x `kindling`. Default kindlings are Plant String, Paper, or Hay blocks. If you add the ore name `kindling` to any item via craft tweaker, it will be able to be used as a fire pit ingredient.

Is that sufficient?

**Comment by Waynekosimoto** [comment]
Latest always latest, yes that's sufficient. Sorry for the spam :/ any chance for a discord?

**Comment by alcatrazEscapee** [comment]
I don't have a specific server for this, but if you have questions feel free to ping me. My user is AlcatrazEscapee#6260

**Comment by Waynekosimoto** [comment]
I can't find your username

**Comment by alcatrazEscapee** [comment]
Check your spelling - that is my name.

**Comment by guillaumearm** [comment]
Hi, thanks for this cool mod, It would be very appreciated to be able to change the fire pit recipe requirements.

For the context, I try to made a modpack that will add several things to do before getting your first wood log, and I want to be able to make a firepit without the need of a `<ore:logWood>`.

can it be considered to add an entry in the config ? or maybe a craftweaker method to add/remove (or override) fire pit recipe ?

In addition, with crafftweaker I cannot add a crafting recipe for the firepit (actually, there is not item, but a tileentity I think)

```
recipes.addShaped("fire_pit_recipe", <notreepunching:fire_pit:0>, [
  [<ore:stickWood>, <ore:stickWood>, null],
  [<ore:stickWood>, <ore:stickWood>, null],
  [null, null, null]
]);
```
