### ISSUE TITLE
ceramic water button with oredict label

### ISSUE THREAD

**Issue by manuelherzog** [alcatrazEscapee/no-tree-punching#57]
Hey,

do you think it would be an useful option to add the oredict name listAllWater Option to the ceramic water bucket? then it would be able to use it in cooking recipes from mods like pam's harvestcraft.

Would be very useful for the beginning of a hardcore modpack with a lot difficulties until you have metals. Especially when default food is nearly useless and you need to cook to get meals that reduce hunger a lot instead of half steps ;)

What do you think about it?

**Comment by alcatrazEscapee** [comment]
No I don't, as it doesn't add any value by itself. If a modpack wants to add an ore dictionary value then it is trivial to do with craft tweaker.
