### ISSUE TITLE
Cant Knap on the SIDE of Stone

### ISSUE THREAD

**Issue by Fortist** [alcatrazEscapee/no-tree-punching#59]
Currently, I can only knap flint on the top of a stone block and not on the side, which is weird since it's a stone block regardless.

**Comment by alcatrazEscapee** [comment]
This was intended - whether it is necessary is up for debate

**Comment by Fortist** [comment]
Thats dumb. It actually should be a bunch of blocks in general but purely the TOP of one (1) block? Same for the wood cutting but I digress,
This has a lot of obtuse things just straight up wrong, subjectively.

**Comment by alcatrazEscapee** [comment]
It's not just one block - its any rock type full block (i.e. Stone, Granite, Diorite, Iron Ore, Obsidian, etc.)
