### ISSUE TITLE
Player still can punch IC2 Rubber Tree

### ISSUE THREAD

**Issue by QuantumStatement** [alcatrazEscapee/no-tree-punching#6]
Minecraft 1.12.2
No Tree Punching 1.1.8
IndustrialCraft 2 2.8.75-ex112
Singleplayer

If player punching IC2 Rubber Tree by bare hands, he still receives Rubber Wood instead of nothing

**Comment by alcatrazEscapee** [comment]
I am currently in the middle of a larger update, but I believe I have a fix for this
