### ISSUE TITLE
[Suggestion] Disable Collection of stone via Rightclick

### ISSUE THREAD

**Issue by MasterEnderman** [alcatrazEscapee/no-tree-punching#60]
Hello,
I'm currently working on a Modpack, where the player needs a specific tool to mine the surface rocks drom your mod. The problem is that the player can easily bypass this features, by collecting the rocks with a simple rightclick. So it would be great, if you could make this a config, that the player have to break the rocks to obtain them.

**Comment by alcatrazEscapee** [comment]
Added in 2.0.10
