### ISSUE TITLE
[Bug] Tree Farm from Ancient Warfare 2 does not get sticks from leaves, ever.

### ISSUE THREAD

**Issue by Thessil** [alcatrazEscapee/no-tree-punching#61]
As the title says, for some reason when leaves are broken by the tree farm, even at 100% chance, they do not drop sticks. This is with both latest builds as of posting.

**Comment by alcatrazEscapee** [comment]
Sticks are dropped from player broken leaves - there is no reason why this would happen unless Ancient Warfare 2's tree farm specifies that to happen. If you want this feature I would suggest opening an issue with them.
