### ISSUE TITLE
Disabling the Quark and Rustic Compat breaks the block drop.

### ISSUE THREAD

**Issue by Fortist** [alcatrazEscapee/no-tree-punching#62]
So disabling the loose rock and cobblestones makes it so the blocks (Basalt, Slate, and Marble) dont drop at all.
I had disabled it because polished basalt and marble would drop rocks instead of the blocks when mined unlike the vanilla versions of polished blocks.
After checking real quick, even the polished blocks drop nothing now.

You should also separate breaking speed changes, and block drop changes (ergo, the rocks) as to not have them tied completely.

**Comment by alcatrazEscapee** [comment]
So I believe I've fixed the following:
 * Polished variants should drop normally, not loose rocks
 * If the compat features are not enabled, no changes should be made to block drops
 * Fixed a world gen crash that happened if you disabled quark / rustic compat.

That should be done in 2.0.11
