### ISSUE TITLE
[Suggestion] Campfire - style in-world crafting

### ISSUE THREAD

**Issue by FastBoye127** [alcatrazEscapee/no-tree-punching#69]
Campfires are created in such a cool way. Is there any way crafttweaker could be implemented so that, for example, a recipe could be made wherein throwing 4 cobblestone, 4 clay, and 4 charcoal on the ground and igniting it would create a vanilla furnace?

**Comment by alcatrazEscapee** [comment]
No. Ask craft tweaker for that feature - It's way outside the scope of NTP.
