### ISSUE TITLE
custom axe's cannot chop wood

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#71]
Custom axe's cannot chop wood into planks (right clicking on a wood block), we need some sort of config to add custom axe'sCustom axe's cannot chop wood into planks (right clicking on a wood block), we need some sort of config to add custom axe's

**Comment by alcatrazEscapee** [comment]
Some axes will work automatically, based on how the mod author implemented them. If it doesn't, you can add the axe to the ore dictionary name `toolAxe`, or `toolWeakAxe` (if you want it to behave like the flint axe).

If you try that and still have an issue, open a new report, but with the specific mod + version + axe that was not working, and I'll take a look

**Comment by Shivaxi** [comment]
How would I add it to the ore dictionary name?  I didn't see any options in the NoTreePunching.cfg to add custom axe's.  The axe in question was the silver axe from Ice And Fire Dragons

**Comment by alcatrazEscapee** [comment]
Use a mod like craft tweaker - It's not a part of NTP. See the relavant tutorial [here](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Ore_Dictionary#Adding_new_ore_dictionary_entries).

**Comment by Shivaxi** [comment]
Okay, I added it to the ore dictionary toolAxe using crafttweaker with <ore:toolAxe>.add(<iceandfire:silver_axe>);

Well it worked for a second, i was able to chop 1 wood block with right click of an axe.  Unfortunately it only worked once, and now the axe seems to be bugged or something.  It won't chop any more blocks with right click, and now wood doesn't even drop when mining the wood normally with the silver axe via left click, as if i have the wrong tool, but it mines fast like its the right tool.

I have no idea what's going on lol

EDIT:  okay apparently the silver axe never worked to mine wood...very weird

EDIT 2:  AH!  I needed <ore:toolAxe>.add(<iceandfire:silver_axe:*>); , the reason it only worked once before is because without the :* it only applies to a full durability axe lol.  So now I can right click chop wood into planks no problem.  However the other problem still persists of not being able to mine/harvest wood normally with left click, so I don't know what's up with that.

**Comment by alcatrazEscapee** [comment]
That's an issue with how Ice + Fire has coded their axe, not something I will be fixing. They haven't added the tool class `axe` to their axe, nor have they extended `ItemAxe`... I would open an issue with them.
