### ISSUE TITLE
[feature request] Clay Tool does not appear to have Craft Tweaker Support

### ISSUE THREAD

**Issue by Winddbourne** [alcatrazEscapee/no-tree-punching#73]
I was very glad to see that there is some craft tweaker support for No Tree Punching but one thing I was actually looking for was a way to make the clay tool more useful. 

My idea was to add the ability to make tinkers construct mud bricks using the mud from mods like the Erebus and the clay tool. I also thought it might be useful for shaping various adobe style blocks from other mods. 

It's a really interesting crafting mechanic. Sort of reminds me of a chisel for unfired clay and perhaps for various dirt products like adobe or mud bricks.

It's not super important, but it would be a nice feature to expand upon.

**Comment by alcatrazEscapee** [comment]
(as you may have guessed by the late reply) I don't have any plans to make this customizable - the in-world crafting mechanics in NTP are not really extensible, and it's not really within the scope of the mod to provide a huge amount of custom crafting mechanics.
