### ISSUE TITLE
silk touch doesnt work if not the right tool for the block

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#74]
As title says, if you have silk touch on say a shovel, and dig a wood block, you don't get the wood block because it's not an axe.  I'm not sure if this is intentional or not but I feel silk touch should be able to override tool requirements and give you the block anyway.

**Comment by alcatrazEscapee** [comment]
This is consistent with Minecraft's default behavior - a silk touch shovel won't mine stone. The only difference is now more blocks require a tool in order to be harvested.
