### ISSUE TITLE
Traverse fir logs can't be chopped with axe.

### ISSUE THREAD

**Issue by InaccurateTank** [alcatrazEscapee/no-tree-punching#75]
As stated in title.  Also as a result the saw doesn't work on them for planks.

On a related note is it possible to change this to a whitelist of blocks for chopping?

**Comment by alcatrazEscapee** [comment]
It should work as long as there's a recipe registered normally for the log -> plank in the crafting grid. It does a scan of all possible wood blocks and finds all recipes that match. Could also be if traverse logs don't match `logWood` ore dictionary.
