### ISSUE TITLE
biomes o' plenty and no tree punching are broken.

### ISSUE THREAD

**Issue by MoonTruther** [alcatrazEscapee/no-tree-punching#79]
So, i'm playing the RLCraft mod pack, and i installed biomes o' plenty to mess around with the wasteland city world generation, and i got bored rather quickly and went back to trying to survive on a normal world, and i noticed if i try to break the trunk of a tree, it simply breaks like in default mine craft, and i can punch it with my fist.

**Comment by alcatrazEscapee** [comment]
What version of NTP do you have?

**Comment by MoonTruther** [comment]
> What version of NTP do you have?

2.0.13

**Comment by alcatrazEscapee** [comment]
This was likely fixed in 5521c384202b78d20738f46f92f4fc10b13680c7, update to 2.0.17
