### ISSUE TITLE
Ice & Fire axes don't chop down logs

### ISSUE THREAD

**Issue by luxlacis** [alcatrazEscapee/no-tree-punching#81]
Sorry to bother you again with this but I reported this issue to the Ice & Fire mod devs and they replied with this (https://github.com/Alex-the-666/Ice_and_Fire/issues/1872).

The issue is that their axes do not break down vanilla logs. I extended the item to `toolAxe` using craft tweaker `<ore:toolAxe>.add(<iceandfire:myrmex_jungle_axe:*>);` and now they break and drop modded logs but not vanilla ones. They do however now have the right click functionality on any log.

I'm using the latest version of the mod.

**Comment by alcatrazEscapee** [comment]
Yes, as I said, the issue was on their end, and they have now fixed it. You'll have to wait for them to publish an updated version that includes that fix. Adding `toolAxe` as an ore dictionary value won't do anything in this case.
