### ISSUE TITLE
dupe bug with tall grass and grass fiber

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#82]
Small issue but, you can essentially get infinite grass fiber by placing down say a rose bush, then cutting it with a knife.  You get the rose bush back and plant fiber.

In the config, there is this:

    # The chance for tall grass to drop plant fiber when broken with a knife
    # Min: 0.0
    # Max: 1.0
    D:tallGrassDropPlantFiberChance=0.5

However setting this to 0 disables it for ALL grass, not just tall grass as it seems to imply

**Comment by alcatrazEscapee** [comment]
Tall grass in that sense is meaning "not grass blocks"
