### ISSUE TITLE
Help me using custom tools to break logs/planks into planks/sticks

### ISSUE THREAD

**Issue by guilherme-coelho** [alcatrazEscapee/no-tree-punching#84]
Hey, sorry if I'm posting on the wrong place. However, I'm trying to make the Hatchet/Lumberaxe from TConstruct to be able to chop wood/planks like the Axe from the game. They are "different" tools, so they aren't type axe and can't break it.

Look, I'm a total noob to modding. But if you can point me a direction on how to do it, I would be very grateful.

**Comment by alcatrazEscapee** [comment]
At the moment, you can use ore dictionary values to accomplish this. However, I've just improved it to match the same logic that is used to breaking checks, meaning it should in general be much more reliable.

**Comment by guilherme-coelho** [comment]
Okay, I just download the new version. I do think that I'm understanding it more!

So sorry for annoying you with these questions, but what I need to do is (correct me if I'm wrong):
1 - Import the class from TConstruct and make it a dependancy
2 - At the "PlayerInteractionHandler.java" I create a new ore dictionary value for the Hatchet/Lumberaxe
3 - I do the same at the "WoodRecipleHandler.java" 

And it should work right? Again, sorry for being annoying.

**Comment by alcatrazEscapee** [comment]
No, you need to do none of that. It should be automatic.

Edit: And adding an ore dictionary value doesn't even need a mod - you can use craft tweaker for that.

**Comment by guilherme-coelho** [comment]
It's working!!! OMG you did it so fast! Thank you so much man. The people on my server will love the news!
