### ISSUE TITLE
NPT causing weird conflict with spongeforge

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#89]
NPT as far as we've tested from 2.0.13 to 2.0.19 causes an interesting conflict in spongeforge servers where stuff like ores, wood, and stone won't drop any items at all.  The only way to fix seems to be by adding all these ores and wood and stone into the "always breakable" config section of NPT

**Comment by alcatrazEscapee** [comment]
Try reporting this to spongeforge - I don't know what it would be doing that bypasses tool harvestability checks.

**Comment by LXGaming** [comment]
Assuming your running RLCraft, remove the MultiMine mod from your server.
For more information: https://github.com/SpongePowered/SpongeForge/issues/2997#issuecomment-538916495
