### ISSUE TITLE
saw recipes still not working

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#90]
Updated and tried 2.0.19

Saws cannot be used in a crafting table anymore to cut logs into planks, logs into sticks, or planks into sticks

![image](https://user-images.githubusercontent.com/10459358/66231017-718b4d80-e6b3-11e9-8bc1-c0a696ffc910.png)

the strange part is that at least for saw + log its showing a plank output if looking in JEI

![image](https://user-images.githubusercontent.com/10459358/66231081-941d6680-e6b3-11e9-80e4-e35a60a4e6e2.png)

But only for Fir Wood, the custom wood in Traverse.

this is with both these options set to true:

B:enableAdvancedRecipeReplacement=true
B:replaceLogRecipes=true

I also removed all my own recipes for the saw in my crafttweaker to test, so shouldnt be any sort of conflict there

**Comment by alcatrazEscapee** [comment]
It's working fine for me. Are you removing log -> plank recipes via craft tweaker perhaps? Or removing the recipes (as you said you were before)? Or removing / changing ore dict names for the saw?

**Comment by Shivaxi** [comment]
My apologies, you're correct, I forgot to remove the line where i removed all wood recipes to add my own.  It's working now.
