### ISSUE TITLE
Redstone Ore not dropping (even after adding to always-breakable in config)

### ISSUE THREAD

**Issue by craving-death** [alcatrazEscapee/no-tree-punching#94]
https://github.com/alcatrazEscapee/no-tree-punching/issues/89

Same issue as here, all ores seem to work fine minus Redstone.

I added "minecraft:redstone_ore" to notreepunching.cfg always breakable and still does not drop.

Is there another block ID it goes by?

SpongeForge server

**Comment by alcatrazEscapee** [comment]
Duplicate #89

**Comment by craving-death** [comment]
is there no workaround for this at all you have found? that's what i was really hoping for opening the issue
