### ISSUE TITLE
Modded Axes don't drop logs. they will break but they will not drop.

### ISSUE THREAD

**Issue by AisuTistoto223** [alcatrazEscapee/no-tree-punching#95]
![image](https://user-images.githubusercontent.com/47762838/66707496-66699a80-ed0f-11e9-99db-49c112e2fa8c.png)

**Comment by alcatrazEscapee** [comment]
1. which mod(s)?
2. which axe(s)?
3. which log(s)?
and 4. can you reproduce it with just NTP and said other mod(s)?

If you have a specific issue, then you need to provide more details than that, and I'll be happy to look into it. Otherwise, I'm not able to do anything.
