### ISSUE TITLE
TekTopia AI gets stuck on ground rocks

### ISSUE THREAD

**Issue by Barerock** [alcatrazEscapee/no-tree-punching#96]
Thought I'd let both authors know,
I added TekTopia to RLCraft and the NPCs get stuck on the rocks and spin around in circles permanently.

**Comment by alcatrazEscapee** [comment]
This sounds like the same issue as #91 - it should be fixed in more recent versions of NTP. What version are you currently using? Other than that I think it would be TekTopia's pathfinding, because I know it rewrites the entire pathfinding system to work with the new villagers.

**Comment by Barerock** [comment]
91 seems to be a collision issue. The villagers can't seem to path off of the block with the rock on it even though they can easily be hit off of the block and resume normal pathing. It's definitely a Tektopia issue, but I thought I'd let you know for future reference. I'll update with a version number tomorrow at some point as it's bed time for me.

**Comment by alcatrazEscapee** [comment]
Yes, that's exactly what's happening here - they get stuck because the rock is marked as non-collidable, but not passable, which is what is used for pathfinding. That was fixed in a later version of NTP, depending on what version of RLCraft you are using you may just need to update NTP and the problem will go away.

**Comment by Barerock** [comment]
Ah. Well I'll just update the mods myself as I've kind of Frankensteined it into my own little nightmare modpack. Thanks for the quick response!

**Comment by alcatrazEscapee** [comment]
Actually built and uploaded the update that fixes this, should work now.
