### ISSUE TITLE
minor incompatibility with realistic torches

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#98]
the fire pit you can create gives normal vanilla torches when right clicking it with sticks.  i use realistic torches in my modpack, with a custom recipe for "permanent torches" aka vanilla torches.  So obviously this breaks the mod pack a little when you're able to just get 'permanent' torches via this method.

I don't know if you'd be able to add some compatibility for realistic torches so the fire pit gives a realistic torch instead, or a config option to disable this feature, that or I can just disable the fire starter item (which is the only thing that can make a fire pit right?  i dont think flint n steel works) which would be fine too since I have another matchbook item thats easy to craft early game

**Comment by Shivaxi** [comment]
on further testing, people who already have fire pits in their world will still be able to use and re-light them for infinite torches.  I tried blocking the fire pit with Reskillable by giving it a ridiculously high level requirement, but it doesnt recognize notreepunching:fire_pit possibly because its not a registered item/block

**Comment by MagmaSlime123** [comment]
This ain't gonna be fixed. No updates for almost a year.

**Comment by alcatrazEscapee** [comment]
#111
