### ISSUE TITLE
knife recipes still not showing for flint knives

### ISSUE THREAD

**Issue by Shivaxi** [alcatrazEscapee/no-tree-punching#99]
same issue as https://github.com/alcatrazEscapee/no-tree-punching/issues/88

I think you fixed this but didn't release an update for it?

**Comment by alcatrazEscapee** [comment]
nuts

**Comment by Shivaxi** [comment]
Lmao

**Comment by alcatrazEscapee** [comment]
Actually built + uploaded now, should be fixed.
